### ISSUE TITLE
Item values can not be updated/initialized at system start up

### ISSUE THREAD

**Issue by planesweep** [openhab/openhab#1379] opened 2014-08-30 17:04 UTC
Hi,

I always get the following error at start up:

18:58:31.051 INFO  o.o.m.c.i.ModelRepositoryImpl[:97]- Refreshing model 'heating.sitemap'
18:58:31.262 INFO  o.o.m.c.i.ModelRepositoryImpl[:97]- Refreshing model 'rrd4j.persist'
18:58:31.590 INFO  o.o.m.c.i.ModelRepositoryImpl[:97]- Refreshing model 'heating.rules'
18:58:33.011 INFO  o.o.m.script.Initialization[:53]- Initialization is set to ON
18:58:34.125 WARN  o.o.c.a.i.AutoUpdateBinding[:103]- InstantiationException on
18:58:37.226 INFO  o.o.m.script.Update Heating[:53]- Bedroom_Temp is set to 17.0
<b>18:58:37.248 ERROR o.o.m.r.i.engine.RuleEngine[:267]- Error during the execution of startup rule 'Initialize heating actuators and system': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null</b>
18:58:37.272 INFO  o.o.m.c.i.ModelRepositoryImpl[:97]- Refreshing model 'heating.script'
18:58:37.369 INFO  o.o.m.c.i.ModelRepositoryImpl[:97]- Refreshing model 'heating.items'

I am a little bit frustratet because I have wasted much time to find the error but I don't get it.
One log line before I get an valid log output. In my opinion there is some erro in loading order because 'heating.rules' are loaded before  'heating.items' - see lines Refreshing model 'heating.rules' and Refreshing model 'heating.items'.

<b>Rule</b>
```
rule "Initialize heating actuators and system"
	when 
		System started
	then		

	Temperatures?.members.forEach(aTemperatureItem|{
			logInfo("Update Heating","{} is set to {}",aTemperatureItem.name, "17.0")
			postUpdate(aTemperatureItem, "17.0")			
		}		
	)
end
```
<b>Items</b>
```
/* Schlafzimmer */
Group Bedroom														<settings>		(All)
Switch Bedroom_Auto_Control		"Automatische Steuerung" 			<heating> 		(Bedroom)
Number Bedroom_Temp 			"Temperatur [%.1f °C]"				<temperature> 	(Bedroom, Temperatures) { openenergymonitor="bedroomTemperature:JS(divideby10.js)" }
Number Bedroom_Temp_Max 		"Maximum [%.1f °C]"					<temperature> 	(Bedroom, Temperatures)
Number Bedroom_Temp_Min 		"Minimum [%.1f °C]"					<temperature> 	(Bedroom, Temperatures)
Number Bedroom_Temp_Setpoint	"Temperatur [%.1f °C]" 				<temperature>	(Bedroom, Setpoints)
Switch Bedroom_Heating_Switch	"Schlafzimmer" 						<heating>		(Bedroom, Heating) {exec="<[heatingControl state Bedroom:3600000:REGEX((.*?))] >[ON:heatingControl on Bedroom] >[OFF:heatingControl off Bedroom]" }
Number Bedroom_Heating_Rate		"Heizrate [%d %%]"					<heating>		(Bedroom)
```

*System*
Raspberry PI 
Linux raspberrypi 3.12.24+ #694 PREEMPT Tue Jul 15 17:34:35 BST 2014 armv6l GNU/Linux
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)
Openhab 1.5

Are there any hints?

**Comment by Testato** [comment] 2015-07-12 08:08
Same problem here, whit OA 1.7.0 and the Demo example plus some sensors.
Is there news on this bug ? I use BeagleBoneBlack board on Debian

```
2015-07-12 08:28:05.839 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v1.7.0).
2015-07-12 08:28:16.111 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - mDNS service has been started
2015-07-12 08:28:17.064 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - Service Discovery initialization completed.
2015-07-12 08:28:17.150 [INFO ] [.io.transport.mqtt.MqttService] - MQTT Service initialization completed.
2015-07-12 08:28:17.159 [INFO ] [o.i.t.m.i.MqttBrokerConnection] - Starting MQTT broker connection 'dp_mosquitto'
2015-07-12 08:28:25.316 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'mysql.persist'
2015-07-12 08:28:27.273 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'Domino.items'
2015-07-12 08:28:38.087 [INFO ] [penhab.io.rest.RESTApplication] - Started REST API at /rest
2015-07-12 08:28:40.037 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'Domino.sitemap'
2015-07-12 08:28:42.449 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'Domino.script'
2015-07-12 08:28:44.196 [INFO ] [.o.u.w.i.servlet.WebAppServlet] - Started Classic UI at /openhab.app
2015-07-12 08:28:50.622 [INFO ] [.service.AbstractActiveService] - HTTP Refresh Service has been started
2015-07-12 08:28:53.609 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'Domino.rules'
2015-07-12 08:29:01.967 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Initialize light states': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null
2015-07-12 08:29:05.123 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Initialize heating states': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null
2015-07-12 08:29:06.229 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Initialize contact states': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null
2015-07-12 08:29:10.815 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Update max and min humidex': cannot invoke method public abstract org.openhab.core.types.State org.openhab.core.persistence.HistoricItem.getState() on null

**Comment by mknet** [comment] 2015-10-09 10:58
I got the same log entries. Have you guys find something out in the mean time?

I'm using a docker container on OSX: https://hub.docker.com/r/tdeckers/openhab/

Thx!

**Comment by teichsta** [comment] 2015-10-18 18:27
could this be duplicate of #736?

**Comment by steve-bate** [comment] 2016-04-09 15:12
See duplicate issues like #3293 or #2586.

**Closed by steve-bate** 2016-04-09 15:12 UTC
Labels: about-to-be-closed, duplicate
