### ISSUE TITLE
Modbus binding (in serial mode) does not handle Modbus Exception Responses in any way

### ISSUE THREAD

**Issue by mbs38** [openhab/openhab#3546] opened 2015-12-14 13:14 UTC
Seems to apply to serial mode only.

A standard Modbus Exception Response (as outlined here: http://www.simplymodbus.ca/exceptions.htm) sent by a Modbus device is not recognized by the binding. Instead, these responses are deemed inclompete and an IOException "Error reading response" is thrown. This leaves the user with no way of knowing whether there is a real problem or if he/she has just tried to, for example, access a non existent register/coil/input on the Modbus device. 
##

**Comment by ssalonen** [comment] 2015-12-22 20:30
You are right that error messages are not quite self-explanatory. I have actually worked on improved error messages in [my branch](https://github.com/ssalonen/openhab/tree/modbus-connection-fixes-error-messages/bundles/binding/org.openhab.binding.modbus) -- it's must-have to have better error messages even during developmnet. In my branch you can see the exact error code as WARN level (as referenced in [in the page you linked](http://www.simplymodbus.ca/exceptions.htm)).

I have been also thinking that different exception should be handled in a different way. In the current implementaion all kind of exceptions (even recognized modbus exceptions) are handled the same way -- connection is reseted. This is completely unnecessarily. The new branch [introduces error handling](https://github.com/ssalonen/openhab/blob/modbus-connection-fixes-error-messages/bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java#L278) that point out the root cause: [modbus error or IO error](https://github.com/ssalonen/openhab/blob/modbus-connection-fixes-error-messages/bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java#L349) or [transaction id mismatch](https://github.com/ssalonen/openhab/blob/modbus-connection-fixes-error-messages/bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java#L355).

I would like to get any feedback for the changes! Is warn level too high for modbus errors, or should we stick with debug level?

**Comment by mbs38** [comment] 2015-12-26 19:11
Classic timeout (the Modbus device does not respond within the set time limit) is certainly worth to be a warn level error. Otherwise a Modbus device could disappear unnoticed - that's not good.
However, if the user is trying to do things the given Modbus device does not support it would probably be a lot more user friendly to throw a warn level error as well. Something that points into the direction "yes your device responds correctly but you are trying to do something it doesn't support"

**Comment by ssalonen** [comment] 2016-06-08 16:46
PR #4226 (which is now merged) should improve logging a lot. Can you try with the new version?

**Comment by mbs38** [comment] 2016-06-09 12:02
Unfortunately my studies+exams take up all my time atm. I'll do some checks in a couple of weeks. Btw I've just moved my rather big modbus serial installation to openhab 2 and it's running well at 2600/polls a minute with 17 devices on the bus.

**Comment by 9037568** [comment] 2016-12-17 13:44
Hopefully fixed via PR #4226. Please start a new issue if additional problems are found.

**Closed by 9037568** 2016-12-17 13:44 UTC
Labels: enhancement

**Comment by mbs38** [comment] 2016-12-18 17:25
I'm sorry - I've completely forgotten this issue. Unfortunately it has not been fixed by PR #4226.

**Comment by ssalonen** [comment] 2016-12-18 19:07
Thanks . What is the behavior exactly currently with latest development version?
