### ISSUE TITLE
Android App crashes if dimmer is set to undefined

### ISSUE THREAD

**Issue by rvfh** [openhab/openhab#4439] opened 2016-06-03 12:38 UTC
## Expected Behavior
Display dimmer in grey color or at value 0

## Current Behavior
App crashes when navigating to page containing the dimmer

## Possible Solution
treat UNDEF as 0 for dimmers

## Steps to Reproduce (for bugs)
1. Add dimmer item to items
2. send value UNDEF to dimmer item
3. open Android App and navigate to page containing dimmer item
4. Read message "openHAB has stopped"

## Context
My device sends UNDEF as value when the regulator is stopped or not receiving input temperature values for a while

## Your Environment
* Version used: 1.8.3
* Environment name and version: HABDroid v1.8.0.0
* Operating System and version: Android 6.0.1, build MOB30H

**Comment by 9037568** [comment] 2016-06-04 14:33
There's a separate [bug tracker for android](https://github.com/openhab/openhab.android/issues). 

This ticket appears to be a duplicate of [ticket 185](https://github.com/openhab/openhab.android/issues/185) logged there.

If you have evidence that there's a problem in OpenHAB itself, please reopen this ticket.

**Closed by 9037568** 2016-06-04 14:33 UTC
Labels: android, duplicate

**Comment by rvfh** [comment] 2016-06-04 14:42
Nope. Sorry I didn't know about the other tracker. Will check ticket 185
there. Thanks for your work on openHAB!
