### ISSUE TITLE
Fix logging of Rrd4J PersistenceService for unsupported Types

### ISSUE THREAD

**Issue by teichsta** [openhab/openhab#2979] opened 2015-07-28 21:42 UTC
see #1300 for details
##

**Comment by teichsta** [comment] 2015-07-28 21:43
@J-N-K would you mind taking care of this?

**Comment by petrklus** [comment] 2015-07-29 07:36
Thank you very much guys for your replies. Just a thought on this - shouldn't there be a bit more "loud" warning when users try to store unsupported types?

For example, I would expect error to be thrown when trying to store ColorItem into RRD4J datastore.

**Comment by J-N-K** [comment] 2015-07-29 15:36
This is a good question. Currently no error is reported if a cast to DecimalType returns a value. I'll fix the wrong logging first and it shpuld be discussed what to do if the user tries to store an incompatible type. These are at least Call, String, DateTime and Color.

**Comment by J-N-K** [comment] 2015-07-29 15:42
see PR #2983

**Comment by petrklus** [comment] 2015-07-29 15:47
@J-N-K thank you! And I agree - it is confusing at best - even if the logger returns what is actually stored, then it still does not restore properly.

For example, as described in #1300 - the restore actually does not create a correct object (HSBType) but rather the simple DecimalType. I suspect that for colour items, brightness is extracted & stored. 

The problem is that rather than restoring as correct HSBType with no saturation / generic hue + restored brightness, we get DecimalType. This breaks any script that is actually using the Color item in any more extended sense.

**Comment by J-N-K** [comment] 2015-07-29 16:04
This happens because mapToState checks if 

* the item is a SwitchItem (and not DimmerItem) and then assigns OnOffType or
* the item is a ContactItem and then assigns OpenClosedType and finally
* assumes all other items are correctly represented by DecimalType

Basically all unsupported should not be stored at all as there is no possibility to restore them correctly.

**Comment by steve-bate** [comment] 2015-11-19 22:41
Can this issue be closed now that the PR is merged?

**Comment by J-N-K** [comment] 2016-11-21 08:19
IMO this is a limitation that has to be documented. There is now way to store complex types in RRDs.

**Comment by 9037568** [comment] 2016-12-17 13:53
I've added this note to the rrd4j wiki:
````
NOTE: rrd4j is for storing numbers only. Attempting to use rrd4j to store complex datatypes (eg. for restore-on-startup) will not work.
````

@J-N-K , can you wordsmith this if you find it inadequate?

**Closed by 9037568** 2016-12-17 13:53 UTC
Labels: bug
