### ISSUE TITLE
Several Actions aren't properly resolved in Designer

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#1403] opened 2014-09-07 10:59 UTC
Although I copied the action-file to Designer/addons-folder, the actions aren't recognized in the rules-files. So the designer shows errors, where aren't errors at all, also the auto completion does not work (evident)
This Problem exist at least with `Win7-64, Oracle Java7u67-32` and with `openHAB nightly build 716` or older. With the same Installation, `xmpp-action` works as expected, so I think, the problem could be in squeezebox-action-file.

See also http://knx-user-forum.de/openhab/35875-designer-meckert-squeezebox-actions.html

**Comment by udo1toni** [comment] 2015-04-15 18:23
Question: Do I have to import something to rulefile, to make correct use of squeezebox-actions? (Maybe something like **import org.openhab.action.squeezebox** ?)

**Comment by staehler** [comment] 2015-04-17 13:13
I've the same problem unfortunately. Is there no hint, how to get rid of this anoying errors?
Meanwhile this false errors lead to overlook real faults.

**Comment by teichsta** [comment] 2015-04-17 13:24
so you are working with 1.7 SNAPSHOT, right?

**Comment by staehler** [comment] 2015-04-17 15:27
Thats correct. I have the build number not at my hand, but it's quite 
recent (this week)

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 17. April 2015 15:24:36 schrieb Thomas Eichstädt-Engelen 
<notifications@github.com>:

**Comment by teichsta** [comment] 2015-04-17 17:45
strange … when running the Designer from IDE the Squeezebox and xPL Action appear without any problems. So it seems to be an assembly problem …

**Comment by staehler** [comment] 2015-04-17 18:03
Hi Thomas,
hmm, do I need to include a special lib into my rules file? 
I get following error messages:
Couldn't resolve reference to JvmIdentifiableElement 'squeezeboxPlayUrl'.
or
Couldn't resolve reference to JvmIdentifiableElement 'squeezeboxSpeak'.
but the actions work well in openhab.

BTW I get such a error message for my.openhab actions ax´s well:
Couldn't resolve reference to JvmIdentifiableElement 'sendNotification'.

**Comment by teichsta** [comment] 2015-04-17 18:12
as i said it only works when starting the Designer out of the IDE. When running the binary i can reproduce the given problem

**Comment by udo1toni** [comment] 2015-04-18 19:49
:) happy that you can reproduce it :)

**Comment by lolodomo** [comment] 2015-05-24 08:10
Please note that we have the same issue with the MiOS actions too, at least with Designer1.6.2. I have not tested with Designer 1.7.0. So please check the MiOS actions too.

**Comment by watou** [comment] 2015-06-19 07:19
The non-appearance of the new Ecobee actions in the Designer is also an issue.  I have been looking for commonalities across the action bundles as to why some bundles' actions appear and some don't, but I have thus failed to find an explanation.  The Ecobee actions do not appear whether the Designer is run standalone, or from the IDE.  Also, the MiOS plugin is not listed in feature.xml, but adding it does not fix the problem.

**Comment by lolodomo** [comment] 2015-07-26 09:10
Regarding the MiOS actions, I can see using Desinger 1.7 that no error are displayed when you open your rule file. But as soon as you try to modify one rule, errors come back.
So the bug is not yet fixed in 1.7 for MiOS actions.

**Comment by teichsta** [comment] 2015-07-26 09:51
so it seems several actions aren't working. I know of

* Squeezebox
* xPL
* MiOS
* EcoBee

anything else?

**Comment by kaikreuzer** [comment] 2015-07-26 10:09
Well, looking at https://openhab.ci.cloudbees.com/job/openHAB/ws/products/org.openhab.designer.product/target/products/org.openhab.designer.product/win32/win32/x86/plugins/, I see that at least MiOS, EcoBee and my.openHAB are all not contained in the Designer, right?

**Comment by marcelerkel** [comment] 2015-07-26 11:46
The HarmonyHub action is also missing in ./features/org.openhab.designer.feature/feature.xml

**Comment by kaikreuzer** [comment] 2015-07-26 19:36
So to summarize:
The Designer distribution is lacking the bundles
* MiOS
* EcoBee
* my.openHAB
* HarmonyHub

Then, although it includes Squeezebox action and xPL action, it is missing their depedencies on
* io.squeezeserver
* io.transport.xpl

I would assume that if all these were added, there weren't any problem.

**Comment by teichsta** [comment] 2015-07-26 22:16
see #2967 which makes the above mentioned actions visible except my.openHAB

**Comment by staehler** [comment] 2015-07-28 05:30
Not sure if this item fits here:
Designer marks the CallType (Fritzbox-Binding) with this message: "Couldn't resolve reference to JvmType 'CallType'"
    var CallType call = Incoming_Call_No.state as CallType

**Comment by teichsta** [comment] 2015-07-28 21:18
are you sure you've added an import org.openhab.library.tel.CallType in your rules file?

**Comment by staehler** [comment] 2015-07-29 04:59
@teichsta Thanks for the hint. I've imported this lib but the designer message remains (after validating the code). BTW: the rule works, even without this imported lib.

**Comment by teichsta** [comment] 2015-07-31 19:08
see #2967 - made all all Actions (except my.openHAB) available in Designer

**Closed** 2015-07-31 20:46 UTC
Labels: bug, critical
