### ISSUE TITLE
Failed to get local hostname on ubilinux

### ISSUE THREAD

**Issue by shb256** [openhab/openhab#1613] opened 2014-10-29 14:50 UTC
hi guys, i am trying to use openhab on the intel edison. i have installed java 8
on this:  http://www.emutexlabs.com/?option=com_content&view=article&id=201&Itemid=270

root@ubilinux:~/openHAB# java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) Client VM (build 25.20-b23, mixed mode)

it is a standard openhab without any changes. just installed and copyed openhab.cfg
this is the error

14:36:56,720 |-ERROR in ch.qos.logback.core.util.ContextUtil@1ba8d24 - Failed to get local hostname java.net.UnknownHostException: ubilinux: ubilinux: unknown error
	at java.net.UnknownHostException: ubilinux: ubilinux: unknown error
	at 	at java.net.InetAddress.getLocalHost(InetAddress.java:1484)
	at 	at ch.qos.logback.core.util.ContextUtil.getLocalHostName(ContextUtil.java:32)
	at 	at ch.qos.logback.core.util.ContextUtil.addHostNameAsProperty(ContextUtil.java:41)
	at 	at ch.qos.logback.classic.joran.action.ConfigurationAction.begin(ConfigurationAction.java:56)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:276)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:148)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:130)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:157)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:143)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:106)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:56)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:54)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at 	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:33)
	at 	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:27)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at 	at java.lang.Class.newInstance(Class.java:433)
	at 	at org.eclipse.jetty.util.log.Log.initialized(Log.java:156)
	at 	at org.eclipse.jetty.util.log.Log.getLogger(Log.java:430)
	at 	at org.eclipse.jetty.osgi.boot.internal.serverfactory.JettyServerServiceTracker.<clinit>(JettyServerServiceTracker.java:34)
	at 	at org.eclipse.jetty.osgi.boot.JettyBootstrapActivator.start(JettyBootstrapActivator.java:100)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at 	at java.security.AccessController.doPrivileged(Native Method)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at 	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at 	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at 	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.net.UnknownHostException: ubilinux: unknown error
	at 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
	at 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
	at 	at java.net.InetAddress.getLocalHost(InetAddress.java:1479)
	at 	... 45 common frames omitted

**Comment by steve-bate** [comment] 2015-11-20 11:27
@teichsta @kaikreuzer Any update on this issue? Is it still critical?

**Comment by kaikreuzer** [comment] 2015-11-20 12:15
Seems as if @teichsta didn't consider this to be important for OH1, but he has to comment on how he wants to proceed.
For ESH/OH2, this is not an issue, so I just removed the ESH label.

**Comment by teichsta** [comment] 2015-12-25 14:59
hmm … even the latest [orbit build](http://download.eclipse.org/tools/orbit/downloads/drops/R20151118145958/) does only provide logback 1.0.7 whereas the logback fixes comes with 1.0.12 and 1.1.3. Since ESH relies on the orbit builds, too, why is ESH not affected?

@shb256 can you confirm this issue is still present with the latest JDK update?

**Comment by kaikreuzer** [comment] 2015-12-27 16:18
> why is ESH not affected?

Simply because ESH is a framework, not a solution. ESH-based solutions can use any slf4j compliant logging framework and are not constrained to logback.

**Comment by teichsta** [comment] 2016-01-02 21:13
@shb256 any news/updates (see my question above)

**Comment by mrguessed** [comment] 2016-01-30 23:43
Looks like there's a work-around for this issue:
* http://stackoverflow.com/questions/1881546/inetaddress-getlocalhost-throws-unknownhostexception

Basically, Java is using `/etc/hosts` (even when it shouldn't) and it wants to see the hostname (`ubilinux`, in this case) resolvable through it.  Setting it to _alias_ the `localhost`/`127.0.0.1` entry, in `/etc/hosts`, should suffice.

@shb256, can you confirm?

**Comment by teichsta** [comment] 2016-01-31 15:01
thanks for letting us know @mrguessed! So if there is a workaround available (still to be confirmed) i would't consider this issue critical anymore.

@shb256 can you please confirm?

**Comment by steve-bate** [comment] 2016-04-09 00:33
I'm closing this since there appears to be a workaround and it's a Java quirk.

**Closed by steve-bate** 2016-04-09 00:33 UTC
Labels: bug
