### ISSUE TITLE
[owserver] special characters in <serverId> create issue

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#2785] opened 2015-06-23 12:40 UTC
Special characters in <serverId> do not work for the owserver-config.

openhab.cfg:
> owserver:test-01.host=192.168.1.2

*.items:
 > ...... { owserver="<test-01:A7000004XXXXXXXX:Temperature:60000" }

openhab.log:
> 2015-06-23 14:27:50.484 [INFO ] [c.internal.ModelRepositoryImpl] - Refreshing model 'tes_01.items'
> 2015-06-23 14:27:50.500 [ERROR] [i.internal.GenericItemProvider] - Binding configuration of type 'owserver' of item ‘Itemname‘ could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: bindingConfig '<test-01:A7000004XXXXXXXX:Temperature:60000' doesn't contain a valid binding configuration
>  at org.openhab.binding.owserver.internal.OWServerGenericBindingProvider.parseBindingConfig(OWServerGenericBindingProvider.java:117) ~[na:na]
>  at org.openhab.binding.owserver.internal.OWServerGenericBindingProvider.processBindingConfiguration(OWServerGenericBindingProvider.java:91) ~[na:na]
>  at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:348) [org.openhab.model.item_1.7.0.jar:na]
>  at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:324) [org.openhab.model.item_1.7.0.jar:na]
>  at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:171) [org.openhab.model.item_1.7.0.jar:na]
>  at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:390) [org.openhab.model.item_1.7.0.jar:na]
>  at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) [org.openhab.model.core_1.7.0.jar:na]
>  at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) [org.openhab.model.core_1.7.0.jar:na]
>  at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) [org.openhab.model.core_1.7.0.jar:na]
>  at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) [org.openhab.model.core_1.7.0.jar:na]
2015-06-23 14:27:51.038 [INFO ] [.service.AbstractActiveService] - OWServer Refresh Service has been shut down

When I change the serverId from "test-01" to "test01" it works.

tested with openhab 1.7.

**Comment by dominicdesu** [comment] 2015-07-23 18:59
OW binding class javadoc states:
>'serverId' can be any alphanumeric string as long as it is the same in the binding and configuration file. <b>NOTE</b>: The parameter is case sensitive!

This should probably be on the wiki page? 
Now we can also start discussing what alphanumeric means. According to wikipedia, sometimes it is only numbers and letters, sometimes it also includes special characters like . , )(

Question is: Is it acceptable that only alphanumeric strings are allowed (update wiki) or should the binding support any character for the serverID (update code)?

**Comment by 9037568** [comment] 2016-06-19 05:59
Seems like any valid [hostname](https://en.wikipedia.org/wiki/Hostname) should be acceptable here, unless there's some express restriction in the specification for an OWServer.

**Comment by watou** [comment] 2016-06-19 06:15
The binding author chose to leave the serverId as alphanumeric only.  It isn't a hostname, just a key that correlates between the .cfg file and item binding config strings.  I think @dominicdesu's description of the issue is correct, and I vote for updating the wiki and closing the issue.

**Comment by 9037568** [comment] 2016-06-19 12:29
I went through the [One Wire Binding wiki page](https://github.com/openhab/openhab/wiki/One-Wire-Binding), but didn't see anything like this configuration item.

It probably deserves a full item definition somewhere instead of just this fragment, yes?

>...... { owserver="<test-01:A7000004XXXXXXXX:Temperature:60000" }

I don't know how this fragment would fit into a real item definition...

**Comment by watou** [comment] 2016-06-19 13:05
Maybe there is a user of the owserver binding who could take a pass through the wiki page, explaining subjects in more detail that could use improvement?

**Comment by CWempe** [comment] 2016-06-19 15:49
You are confusing the **One-Wire-Binding** and the **EDS-OWServer-Binding**

https://github.com/openhab/openhab/wiki/One-Wire-Binding
https://github.com/openhab/openhab/wiki/EDS-OWServer-Binding

**Comment by 9037568** [comment] 2016-06-19 16:54
Thanks, @CWempe !

I've added a second sentence to this block in the EDS-OWServer-Binding page:
>The `serverId1` corresponds to the device which is introduced in openhab.cfg. This value must match the value in openhab.cfg and must consist only of letters, numbers and periods.

Hopefully this addresses this ticket.

**Closed by 9037568** 2016-06-19 16:54 UTC
Labels: documentation, question
