### ISSUE TITLE
netatmo binding does not seem to work anymore 

### ISSUE THREAD

**Issue by pfleghar** [openhab/openhab#2212] opened 2015-02-28 21:52 UTC
Hi there, 

I am very confused ... it seems that my netatmo binding does work at all anymore on my new Rasperry Pi 2 with Oracle Java 1.7. I have tried with openhab-1.6.2, openhab-1.7.0-841, openhab-1.7.0-868, openhab-1.7.0-869. 

The binding seems to be loaded, and active: 

id	State       Bundle
237	ACTIVE      org.openhab.binding.netatmo_1.7.0.201502280210

Here is the weird part, a tcpdump pointing to dev.netatmo.com claims that there no communication at all to dev.netatmo.com. 

I guess my first question would be, can anybody confirm the netatmo binding working or not working with a Pi 2 with Oracle Java 1.7 and any newer OpenHAB version. 

Thanks a bunch, 
Ralf

**Comment by teichsta** [comment] 2015-03-05 20:14
@abrenk, @clinique could you take care of this one?

**Comment by abrenk** [comment] 2015-03-05 20:21
@teichsta I can take a look at it before the meetup tomorrow, after I've landed in Düsseldorf.

**Comment by pfleghar** [comment] 2015-03-05 23:28
I just took some time and updated to 871 and played around with the refresh timer. I got it to work as soon as I changed the refresh timer to anything else than the default. Could that be? I can offer to stay on track of this, until I have  more reproducible facts.

**Comment by abrenk** [comment] 2015-03-06 13:39
I cannot reproduce your problems. The binding seems to work fine.

You can add the following line to logback.xml to switch on debug logging.
<logger name="org.openhab.binding.netatmo" level="DEBUG"/>

**Comment by teichsta** [comment] 2015-03-13 09:33
ok @pfleghar let's close this issue for now and discuss further technical details on the Google Group. Once we've worked out a possible issue please feel free to enter an issue or reopen this one. Thanks, Thomas E.-E.

**Closed by teichsta** 2015-03-13 09:33 UTC
