### ISSUE TITLE
Zwave: Yale Lock Support

### ISSUE THREAD

**Issue by akkord64** [openhab/openhab#1914] opened 2014-12-31 12:57 UTC
Need to add support for Yale Locks. I have installed some Real Living Locks deadbolts (product YRD210-ZW-0BP). I can successfully bind the device to the network, but the zwave DB does not know about this manufacturer. In HABmin, the device is recognized with the following attributes:

Manufacturer ID 297 (in the node Information section, the ManufacturerID says 129??)
Device ID: aa00
Device Type: 4
Version: 4
Library Type: Slave Enhanced
Protocol Version: 6.4
Application Version: 36.2
Basic Device Class: ROUTING_SLAVE
Generic Device Class: ENTRY_CONTROL
Specific Device Class: SECURE_KEYPAD_DOOR_LOCK

I was unable to find the device in the pepper DB, but I was able to find the Zwave alliance certification.

http://products.z-wavealliance.org/products/687
http://products.z-wavealliance.org/products/687/pics

Z-Wave Protocol Implementation Conformance Statement
Yale Real Living™ Push Button Deadbolt
General Information
Product Identifier: Yale/YRD/ 210
Manufacturer Name: Yale Locks & Hardware
Manufacturer Product Version: 1
Z-Wave Certification #: ZC08-12060010
Z-Wave Product Information
Supports Z-Wave Beaming Technology? Yes
Supports Z-Wave Network Security? Yes
Supports Z-Wave AES-128 Security? Yes
Z-Wave Technical Information
Z-Wave Frequency: United States
Z-Wave Device Class: GENERIC_TYPE_ENTRY_CONTROL / SPECIFIC_TYPE_SECURE_KEYPAD_DOOR_LOCK
Z-Wave Supported Command Classes: COMMAND_CLASS_DOOR_LOCK, COMMAND_CLASS_SCHEDULE_ENTRY_LOCK,
COMMAND_CLASS_ASSOCIATION, COMMAND_CLASS_USER_CODE, COMMAND_CLASS_BASIC,
COMMAND_CLASS_BATTERY, COMMAND_CLASS_SECURITY, COMMAND_CLASS_VERSION,
COMMAND_CLASS_MANUFACTURER_SPECIFIC, COMMAND_CLASS_DOOR_LOCK_LOGGING,
COMMAND_CLASS_PROTECTION, COMMAND_CLASS_TIME_PARAMETERS,
COMMAND_CLASS_ALARM, COMMAND_CLASS_CONFIGURATION, COMMAND_CLASS_TIME
Z-Wave Controlled Command Classes:

**Comment by cxguy** [comment] 2015-04-14 15:36
The lock gives spoken prompts and feedback, so that's likely why there is a language setting.

**Comment by cdjackson** [comment] 2015-05-01 11:27
#1209

**Comment by cdjackson** [comment] 2015-08-01 15:56
Closing this as it's a duplicate of #1209

**Closed by cdjackson** 2015-08-01 15:56 UTC
Labels: duplicate, enhancement
