### ISSUE TITLE
influxdb doesn't restore anymore

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#3173] opened 2015-09-16 16:23 UTC
Hi,

I just updated to Snapshot 1021, restarted openhab and all persited items in influxdb haven't been restored.
There must be a difference at least betwenn Snapshot 1001 and 1021 as the bindings have different size:
    -rw-rw-r-- 1 openhab openhab 2608161 Sep 16 03:51 org.openhab.persistence.influxdb-1.8.0-SNAPSHOT.jar  <== Snap 1021
    -rw-rw-r-- 1 openhab openhab 2609191 Jul 12 03:36 org.openhab.persistence.influxdb-1.8.0-SNAPSHOT.jar  <== Snap 1001

I get this error message during startup (I assume for each persisted item):

2015-09-16 17:41:07.463 [ERROR] [i.i.InfluxDBPersistenceService] - query failed with database error
2015-09-16 17:41:07.504 [ERROR] [i.i.InfluxDBPersistenceService] - database connection error may be wrong password, username or dbname: {}
java.lang.RuntimeException: syntax error, unexpected $end
select value, time from node1_temp where
                                        ^
        at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19) ~[na:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242) ~[na:na]
        at org.influxdb.impl.$Proxy82.query(Unknown Source) ~[na:na]
        at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:110) ~[na:na]
        at org.openhab.persistence.influxdb.internal.InfluxDBPersistenceService.query(InfluxDBPersistenceService.java:328) ~[na:na]
        at org.openhab.core.persistence.internal.PersistenceManager.initialize(PersistenceManager.java:369) [org.openhab.core.persistence_1.8.0.201509160135.jar:na]
        at org.openhab.core.persistence.internal.PersistenceManager.startEventHandling(PersistenceManager.java:186) [org.openhab.core.persistence_1.8.0.201509160135.jar:na]
        at org.openhab.core.persistence.internal.PersistenceManager.addPersistenceService(PersistenceManager.java:149) [org.openhab.core.persistence_1.8.0.201509160135.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
        at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:213) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70) [org.eclipse.equinox.util_1.0.400.v20120917-192807.jar:na]

I'll go back to Snap 1001, which does not show this behaviour.

Regards,
Michael

**Comment by kaikreuzer** [comment] 2015-09-16 18:41
Could this be related to https://github.com/openhab/openhab/issues/2661#issuecomment-140437827?

**Comment by staehler** [comment] 2015-10-08 15:59
For your information: this error remains even in Snapshot 1032.

2015-10-08 17:54:18.113 [ERROR] [i.i.InfluxDBPersistenceService] - query failed with database error
2015-10-08 17:54:18.123 [ERROR] [i.i.InfluxDBPersistenceService] - database connection error may be wrong password, username                                             or dbname: {}
java.lang.RuntimeException: syntax error, unexpected $end
select value, time from Urlaub where
                                    ^
        at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19) ~[na:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242) ~[na:na]
        at org.influxdb.impl.$Proxy94.query(Unknown Source) ~[na:na]
        at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:110) ~[na:na]
        at org.openhab.persistence.influxdb.internal.InfluxDBPersistenceService.query(InfluxDBPersistenceService.java:328) ~                                            [na:na]
        at org.openhab.core.persistence.internal.PersistenceManager.initialize(PersistenceManager.java:369) [org.openhab.cor                                            e.persistence_1.8.0.201510080142.jar:na]
        at org.openhab.core.persistence.internal.PersistenceManager.startEventHandling(PersistenceManager.java:186) [org.ope                                            nhab.core.persistence_1.8.0.201510080142.jar:na]
        at org.openhab.core.persistence.internal.PersistenceManager.addPersistenceService(PersistenceManager.java:149) [org.                                            openhab.core.persistence_1.8.0.201510080142.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
        at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376) [org.eclipse.equinox.d                                            s_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444) [org.ecli                                            pse.equinox.ds_1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416) [org.eclipse.equinox.ds_1.4                                            .1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334) [org.eclipse.equinox.ds_1.4.1.v20120926-2                                            01320.jar:na]
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.1.v201                                            20926-201320.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107                                            ) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861) [org.eclipse                                            .osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.8.2.v20                                            130124-134944.jar:na]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.o                                            sgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)                                             [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771) [org.ecli                                            pse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org                                            .eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214) [org.eclipse.                                            osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433) [org.eclip                                            se.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536) [org.eclipse.equinox.ds                                            _1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:213) [org.eclipse.equinox.ds                                            _1.4.1.v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473) [org.eclipse.equinox.ds_1.4.1.v20                                            120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217) [org.eclipse.equinox.ds_1.4.1.v20120                                            926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816) [org.eclipse.equinox.ds_1.4.1.v201209                                            26-201320.jar:na]
        at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783) [org.eclipse.equinox.ds_1.4.1.                                            v20120926-201320.jar:na]
        at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89) [org.eclipse.equinox.ds_1.4.1.v20120926-201320                                            .jar:na]
        at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70) [org.eclipse.equinox.util_1.                                            0.400.v20120917-192807.jar:na]

**Comment by theoweiss** [comment] 2015-10-08 18:17
Hi Michael,

which influxdb server version are you using?

Regards,
Theo

**Comment by staehler** [comment] 2015-10-08 19:58
Hi Theo,
my influxdb version is 0.8.8. Openhab worked with this influxdb very well, as I didn't change anything at my influxdb installation.
My working OH version is 1.8.0 snapshot 1001.

Kind regards, Michaek

**Comment by staehler** [comment] 2015-10-12 08:20
@theoweiss Are you working on this issue? Can I provide further information?

**Comment by theoweiss** [comment] 2015-10-12 19:59
@staehler I started working on this issue.

**Comment by teichsta** [comment] 2015-10-18 05:55
fyi! I've "managed" to unmerge some important changes to InfluxDB Service through #3125! I reverted all changes to the Service an reapplied the changes that were intended by #3125 (to finally fix #2661) in #3312. Sorry for the inconvenience!

**Comment by theoweiss** [comment] 2015-10-18 16:26
@staehler could you please test the influxdb service again as soon as #3312 is merged.

**Comment by teichsta** [comment] 2015-10-18 17:30
#3312 is merged …

**Comment by kaikreuzer** [comment] 2015-10-18 20:19
And could somebody please also test it on OH2, so that it is confirmed that at least for InfluxDB https://github.com/openhab/openhab/issues/2661 is fixed?

**Comment by theoweiss** [comment] 2015-10-18 22:03
I would test it if no one makes ago.

**Comment by staehler** [comment] 2015-10-19 05:28
Hi Theo,  I will test, but can do it just net week.
Michael

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 19. Oktober 2015 00:03:32 schrieb Theo Weiss <notifications@github.com>:

**Comment by theoweiss** [comment] 2015-10-22 20:08
@kaikreuzer I just tested it on OH2: the service is working well 👍. Is there something to be done on the OH repo?

**Comment by kaikreuzer** [comment] 2015-10-22 20:22
That's good news, thanks!

> Is there something to be done on the OH repo?

Yes, it would be nice if you could do a PR similar to https://github.com/openhab/openhab2/commit/b14195775b1d5e7d710ff01355ba093f0d0fa89b.

**Comment by theoweiss** [comment] 2015-10-22 20:35
Ok, I will give it a shot.

**Comment by staehler** [comment] 2015-10-25 17:41
@theoweiss Hi Theo, you did a great job :-) The above mentioned bug has been fixed. Thanks a lot!

**Comment by theoweiss** [comment] 2015-10-26 18:58
Hi Michael, 

thanks for your testing and feedback.

Regards,
Theo

**Comment by teichsta** [comment] 2015-10-26 20:36
ok, so we can close this one which also fixes #2661, right?

**Closed by teichsta** 2015-10-26 20:36 UTC
Labels: bug

**Comment by theoweiss** [comment] 2015-10-26 21:27
Yes, it's finished except the PR @kaikreuzer mentioned. I'm struggling with my OH2 git repos, therefore I haven't done it yet.
