### ISSUE TITLE
Cannot get influxdb persistence to work with influxdb 0.9(-rc20)

### ISSUE THREAD

**Issue by dtriphaus** [openhab/openhab#2420] opened 2015-04-08 18:06 UTC
Is this known and 0.9 is not yet supported or am i missing something or doing something wrong?

Thx in advance!

Additional Info: influxdb is proxied by an apache to get https support. influxdb is working fine with curl from commandline.

**Comment by teichsta** [comment] 2015-04-08 18:20
@theoweiss @sumnerboy12 could you have a look at this, please? Thanks, Thomas E.-E.

**Comment by sumnerboy12** [comment] 2015-04-08 20:23
InfluxDB v9 is not released/stable yet - I won't be upgrading till that time so can't test unfortunately. More details regarding what the issue is would help tho, error log/traces?

**Comment by dtriphaus** [comment] 2015-04-08 20:50
Here is some information from the logs

2015-04-08 20:01:03.678 INFO  o.o.m.c.i.ModelRepositoryImpl[:79]- Loading model 'influxdb.persist'
2015-04-08 20:01:10.127 DEBUG o.o.p.i.i.InfluxDBPersistenceServiceActivator[:27]- InfluxDB persistence bundle has been started.
2015-04-08 20:01:10.154 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:93]- influxdb persistence service activated
2015-04-08 20:01:18.159 ERROR o.o.p.i.i.InfluxDBPersistenceService[:128]- database connection failed throwing an exception
2015-04-08 20:01:18.160 ERROR o.o.p.i.i.InfluxDBPersistenceService[:201]- database error: null
2015-04-08 20:01:18.161 ERROR o.o.p.i.i.InfluxDBPersistenceService[:246]- database connection does not work for now, will retry to use the database.
2015-04-08 20:02:00.010 TRACE o.o.p.i.i.InfluxDBPersistenceService[:397]- found fractional part
2015-04-08 20:02:00.013 TRACE o.o.p.i.i.InfluxDBPersistenceService[:176]- storing Weather_Windspeed in influxdb 4.83
2015-04-08 20:02:00.447 ERROR o.o.p.i.i.InfluxDBPersistenceService[:189]- storing failed with exception for item: Weather_Windspeed
2015-04-08 20:02:00.448 ERROR o.o.p.i.i.InfluxDBPersistenceService[:201]- database error: 404 page not found

maybe his gives a hint

**Comment by dtriphaus** [comment] 2015-04-09 12:43
As far as i see the API changed (significantly) between 0.8 and 0.9 
I assume this is the reason.

**Comment by theoweiss** [comment] 2015-04-10 20:53
As far as I know the influxdb java api has not yet been ported to influxdb 0.9.RCx. I also would recommend to stay with a version prior to 0.9.
As soon as the java api for 0.9 is available I will give it a try.

**Comment by dtriphaus** [comment] 2015-04-14 20:42
Thanks for your replies, now I use influxdb 0.8.8 and it works like a charm.

**Comment by theoweiss** [comment] 2015-05-22 20:12
Thanks for your testing. I close this issue, the java api is still not ported to 0.9 and influxdb 0.9 isn't yet released. Feel free to open a new as soon as the java api for 0.9 is released..

**Closed by theoweiss** 2015-05-22 20:12 UTC
