### ISSUE TITLE
Multiple Dimmer Items

### ISSUE THREAD

**Issue by schmidtmic** [openhab/openhab#3795] opened 2016-01-14 08:24 UTC
Hello
Right now you can have only one Dimmer item in a group.
If you have multiple dimmers in a room you are stucked.
Example:
Dimmer EG_Kitchen_clining_light "Light1" (EG_Kitchen) { knx="15/3/20+15/3/20, 15/3/21, 15/3/22" }
Dimmer EG_Kitchen_table_light "Light2" (EG_Kitchen) { knx="15/3/20+15/3/20, 15/3/21, 15/3/22" }

Each definition works fine if you use them separately. 
If you use them together the openHAB fail.

  
THX

Michael

**Comment by watou** [comment] 2016-01-14 08:28
believe this is the same as #2900.

**Comment by schmidtmic** [comment] 2016-01-14 08:43
I don't think it is the same issue. In my case the hole interface freeze no matter which browser I use. In issue #2900 the dimmer items are visible. Only the increase/decrease function is not working.

**Comment by watou** [comment] 2016-01-14 09:07
If you open your browser's developer console and try to load the ClassicUI page with multiple dimmers, can you find any JavaScript errors like "cannot set property 'innerhtml' of undefined" or similar?  There seem to be a number of user reports of related problems with Sliders and Dimmers, and yours seems to be in the same "family" of issues that are slated (in #2900) to be fixed in 1.8.1.

**Comment by schmidtmic** [comment] 2016-01-14 09:41
It seems there is a Problem with the innerhtml and it seems to belong the that "family" as you expected. (see screenshot)
![bildschirmfoto vom 2016-01-14 10-31-37](https://cloud.githubusercontent.com/assets/16699734/12320871/5c97ab22-baab-11e5-8085-0ea1e64a7856.png)

**Comment by watou** [comment] 2016-01-14 10:03
Thanks for checking, @schmidtmic.  Hopefully these issues will be sorted in 1.8.1 soon. :smile:

**Comment by sja** [comment] 2016-01-14 10:28
I thing the problem is a Slider without a value-containing label. Can you check that? See https://community.openhab.org/t/classic-ui-1-8-rc/5991/8

**Comment by schmidtmic** [comment] 2016-01-14 11:23
@sja 
You where right. After adding [%s] to the lable field both dimmers showing up!!

Dimmer EG_Kitchen_clining_light "Light1  [%s]" (EG_Kitchen) { knx="15/3/20+15/3/20, 15/3/21, 15/3/22" }

THX

Michael Schmidt

**Comment by teichsta** [comment] 2016-01-31 20:25
fixed with #3796

**Closed by teichsta** 2016-01-31 20:25 UTC
Labels: bug, pr-submitted
