### ISSUE TITLE
MQTT connection gets stale / does not refresh

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab#980] opened 2014-04-15 08:01 UTC
Using default Xively configuration with MQTT persistence, I am having trouble getting consistent results.

After a few hours, the upload stops and I am seeing following messages in the log:

First one:
```
09:51:00.015 ERROR o.e.p.c.m.internal.ClientState[:206]- pi.1397548500389: Timed out as no activity, keepAlive=60,000 lastOutboundActivity=1,397,555,400,339 lastInboundActivity=1,397,555,288,395
```

Subsequent errors:

```
07:54:01.358 ERROR o.o.p.m.i.MqttPersistenceService[:159]- Error sending persistency message for item 'Temp_Garden_Soil' : Client is not connected (32104)
```

The internet is working and as everything else is and the bundles are loaded:
```
osgi> ss mqtt
id      State       Bundle
202     ACTIVE      org.openhab.io.transport.mqtt_1.4.0
224     ACTIVE      org.openhab.persistence.mqtt_1.4.0
226     ACTIVE      org.openhab.binding.mqtt_1.4.0
```

The only fix I've found was to stop the `org.openhab.io.transport.mqtt` bundle and start it again:

```
osgi> stop "202"
07:54:37.268 INFO  o.o.i.t.mqtt.MqttService[:130]- Stopping connection xively
07:54:37.508 ERROR o.o.i.t.m.i.MqttBrokerConnection[:500]- Error closing connection to xively.
org.eclipse.paho.client.mqttv3.MqttException: Client is disconnected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:27)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:405)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:524)
	at org.eclipse.paho.client.mqttv3.MqttClient.disconnect(MqttClient.java:250)
	at org.eclipse.paho.client.mqttv3.MqttClient.disconnect(MqttClient.java:243)
	at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.close(MqttBrokerConnection.java:497)

osgi> start "202"
07:55:00.347 INFO  o.o.i.t.mqtt.MqttService[:102]- MQTT Service initialization completed.
07:55:00.370 INFO  o.o.i.t.m.i.MqttBrokerConnection[:106]- Starting MQTT broker connection 'xively'
```

After this, all is working again and uploading without trouble.

Is the MQTT missing some kind of connection refresh/keepalive?

**Comment by harisjmd** [comment] 2015-07-24 09:09
2015-07-24 06:23:45.895 [ERROR] [.c.mqttv3.internal.ClientState] - openhab: Timed out as no activity, keepAlive=60,000 lastOutboundActivity=1,437,707,889,862 lastInboundActivity=1,437,707,851,920
2015-07-24 06:23:53.489 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - Error starting consumer
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:138) ~[na:na]
	at java.lang.Thread.run(Thread.java:744) ~[na:1.8.0]
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[na:1.8.0]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:56) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:100) ~[na:na]
	... 1 common frames omitted
2015-07-24 06:24:01.237 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - Error starting consumer
org.eclipse.paho.client.mqttv3.MqttException: Client is not connected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:27) ~[mqtt-client-0.4.0.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:132) ~[mqtt-client-0.4.0.jar:na]
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:657) ~[mqtt-client-0.4.0.jar:na]
	at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:282) ~[mqtt-client-0.4.0.jar:na]
	at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:275) ~[mqtt-client-0.4.0.jar:na]
	at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.startConsumer(MqttBrokerConnection.java:480) [org.openhab.io.transport.mqtt_1.7.0.jar:na]
	at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.start(MqttBrokerConnection.java:124) [org.openhab.io.transport.mqtt_1.7.0.jar:na]
	at org.openhab.io.transport.mqtt.internal.MqttBrokerConnectionHelper.run(MqttBrokerConnectionHelper.java:37) [org.openhab.io.transport.mqtt_1.7.0.jar:na]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0]
2015-07-24 06:24:08.841 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - MQTT connection to broker was lost
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:138) [mqtt-client-0.4.0.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[na:1.8.0]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:56) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:100) [mqtt-client-0.4.0.jar:na]
	... 1 common frames omitted
2015-07-24 06:24:17.856 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - MQTT connection to 'mosquitto' was lost: Connection lost : ReasonCode 32109 : Cause : null
2015-07-24 06:24:17.906 [INFO ] [o.i.t.m.i.MqttBrokerConnection] - Starting connection helper to periodically try restore connection to broker 'mosquitto'
2015-07-24 06:24:33.255 [INFO ] [o.i.t.m.i.MqttBrokerConnection] - Starting MQTT broker connection 'mosquitto'
2015-07-24 06:37:53.777 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - MQTT connection to broker was lost
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:138) [mqtt-client-0.4.0.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[na:1.8.0]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:56) ~[na:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:100) [mqtt-client-0.4.0.jar:na]
	... 1 common frames omitted

this is happening to me for the last 2 days at night when nothing happens (see time) and openhab freezes  (running on pi b+) 
having in the addons the mqtt binding and persistence

am i doing something wrong?

mqtt:mosquitto.url=tcp://localhost:1883
mqtt:mosquitto.clientId=openhab
mqtt:mosquitto.qos=1
mqtt:mosquitto.retain=true

and i have an arduino UNO connected with mqtt on raspberry

thanks in advance

**Comment by sebastiankutschbach** [comment] 2015-08-30 19:40
Same to me. I am struggling with this kind of connection losses every 3 days.
Increasing the keepAlive time from 60 to 120 did improve the situation but did not fix this bug permanently.
Any things I can do for further analysis? Do you need any logs?

**Comment by harisjmd** [comment] 2015-08-30 20:32
thanks for ur answer..!;) I changed it to 400 i think.. but the problem was the raspberry getting out of ram.. recently I transferred it to an ubuntu server and was working fine for 3 days.. after many changes i figure out that was the subcribe function that has a bug and after approximately 1 hour it stopped communicating with the main server..publishes from the arduino to the server were getting through but not the subscribes back to the arduino..

**Comment by sebastiankutschbach** [comment] 2015-08-31 09:52
I didn't get your answer completely. Do you mean that there is a bug in the subscribe-method of openHAB Mqtt-Binding? What do you mean by publishes go through to the arduino and no subscribes back?
You are publishing messages to the broker from openHAB and the arduino receives them but the publishes from the arduino do reach the broker but not openHAB?

**Comment by harisjmd** [comment] 2015-08-31 10:53
ok the above problem that i posted has never showed again after i transferred openhab to an ubuntu server but this problem with arduino still occurs ..what shall i do?

openhab --> arduino  : not ok  (arduino stops subscribing to the given topics but the broker sends correctly the  messages)
openhab <-- arduino : ok (publishes ok to the broker)

also here is the arduino file
https://drive.google.com/file/d/0B8Zkx3s4dBt3ZW0wcGNWOUlrUW8/view?usp=sharing

is there a problem with my sketch?

**Comment by teichsta** [comment] 2015-10-16 11:47
> is there a problem with my sketch?

it might be a good idea to transfer this research discussion to https://community.openhab.org. Since the original issue never occurred again i close this. Please reopen in case …

**Closed by teichsta** 2015-10-16 11:47 UTC
Labels: bug
