### ISSUE TITLE
stiebelheatpump tests failing

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#3933] opened 2016-01-31 04:51 UTC
When building from the latest master code, a failure occurs in the tests for the stiebelheatpump binding.

    org.openhab.binding.stiebelheatpump.internal.StiebelHeatPumpException:  
    javax.xml.bind.UnmarshalException 
    - with linked exception:
    [com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.]
    at org.openhab.binding.stiebelheatpump.internal.ConfigParser.unmarshal(ConfigParser.java:103)
    at org.openhab.binding.stiebelheatpump.internal.ConfigParserTest.CreateParserConfiguration(ConfigParserTest.java:46)

**Comment by watou** [comment] 2016-01-31 08:57
Hmmm, the current master worked for me.  Any chance there are old artifacts in your build environment?
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Running org.openhab.binding.stiebelheatpump.internal.ConfigLocatorTest
Loading heat pump configuration file for 2.06.xml
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.332 sec - in org.openhab.binding.stiebelheatpump.internal.ConfigLocatorTest
LoadResourceFiles(org.openhab.binding.stiebelheatpump.internal.ConfigLocatorTest)  Time elapsed: 0.305 sec
Running org.openhab.binding.stiebelheatpump.internal.ConfigParserTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.211 sec - in org.openhab.binding.stiebelheatpump.internal.ConfigParserTest
CreateParserConfiguration(org.openhab.binding.stiebelheatpump.internal.ConfigParserTest)  Time elapsed: 0.126 sec
LoadParserConfigurationFromResources(org.openhab.binding.stiebelheatpump.internal.ConfigParserTest)  Time elapsed: 0.081 sec
Running org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest
Tests run: 29, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.085 sec - in org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest
testParseSettingsHeatingProgram(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec
testParseSettingsDryHeatingProgram(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec
testParseByteToHex(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testParseTime2(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest) skipped
testParseSettingsEvaporator1(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testParseSettingsEvaporator2(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec
testwriteP04DHWTemperatureStandardMode(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.003 sec
testParseTime(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testParseFindAndReplace(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0 sec
testParseCurrentValues(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec
testParseSettingsHeating1(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec
testParseSettingsHeating2(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec
testParseOperationCounters(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testWriteTime(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testDataAvailable(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testParseVersion(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testParseSettingsDomesticWaterProgram(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec
testParseSettingsDomesticWater(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec
testParseSettingsAbsenceProgram(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testParseSettingsNominalValues(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.01 sec
testParseSettingsCirculationPump(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testParseSettingsVentilation(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec
testDataSet(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0 sec
testParseSettingsVentilationProgram(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.012 sec
testAddDuplicatesInRequest1(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testAddDuplicatesInRequest2(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.001 sec
testHeader(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0 sec
testwriteSettingsDomesticWaterProgram(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest) skipped
testParseSettingsRestartAndMixerTime(org.openhab.binding.stiebelheatpump.protocol.StiebelHeatPumpDataParserTest)  Time elapsed: 0.002 sec

Results :

Tests run: 32, Failures: 0, Errors: 0, Skipped: 2

[INFO] All tests passed!
```

**Comment by 9037568** [comment] 2016-01-31 13:27
Not under the openhab tree. I just recently destroyed that completely and
let it rebuild itself.
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by 9037568** [comment] 2016-01-31 14:04
For the sake of completeness, I tried this yet again, and this time it worked. No idea why. Makes absolutely no sense, but there it is.

**Comment by 9037568** [comment] 2016-01-31 14:09
Looks like I lied. I forgot I had commented this binding out of the pom... After restoring it, the build has gone back to failing.

**Comment by teichsta** [comment] 2016-01-31 23:13
the build forks for me (and the build server who builds regular at night). I'll close this this issue for now since it isn't reproducible. Please feel free to reopen once you can reproduce it …

**Closed by teichsta** 2016-01-31 23:13 UTC
