### ISSUE TITLE
Rule trigger 'changed from to' does not work for string items

### ISSUE THREAD

**Issue by gregeva** [openhab/openhab#2552] opened 2015-05-06 10:28 UTC
Affected use-case/example:

    rule Alarm_Away
    when
            Item cntAlarm changed from "Disarmed" to "Armed-Away"
    then
            pushover("Alarm system went to away.")
    end

It is unclear if this is normal operation or not, as the documentation references change from and to <STATE>, and I am not sure if a string value is considered a state or not.

The problem has been reported in the group, and the user is using a 1.7 SNAPSHOT build.
https://groups.google.com/forum/#!topic/openhab/nWlt0FT8Vqk

**Comment by J-N-K** [comment] 2015-05-11 09:26
There is a problem with "changed from ... to ..." rules with String items

Item test changed from state1 to state2

works perfectly fine, if state1 and state2 are strings which only contain alpanumeric characters without any spaces.

It will not work with strings containing a space or hyphen (the string is truncated, i.e. instead of Test-String only Test is stored as the state). If the string is included in quotes, it is not truncated, however the quotes are stored, too. because of that the comparison of test.state with state1 fails.

This is at least not the expected behaviour, if not a bug. I would expect that using quotes is properly supported (i.e. they are either stripped before the compare-state is stored or ignored during the comparison).

The latter could easily be implemented in RuleTriggerManager, but to me the first seems to be the better solution.

(copied from issue #2559 for easier reference)

**Comment by steve-bate** [comment] 2015-11-19 23:48
Since the PR is merged, can we close this issue?

**Comment by gregeva** [comment] 2015-11-23 17:27
I would say that you can, as I think this is not only merged, but fixed.




*Greg Eva*
*geva@ge-volution.eu <geva@ge-volution.eu>*
www.gE-volution.eu
France : +33 4 81 68 09 64
Canada : +1 226 476 1192
iNum : +833 51 00 09 90 28 81

**Closed** 2015-11-23 20:06 UTC
Labels: enhancement
