### ISSUE TITLE
SagerCaster binding must not depend on org.openhab.core.persistence

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab#3754] opened 2016-01-10 19:39 UTC
The SagerCaster binding imports `org.openhab.core.persistence` and `org.openhab.core.persistence.extensions`, which breaks the architecture, since bindings should not directly access the persistence services.
Specifically, this is incompatible with openHAB 2 and thus makes this binding incompatible.

**Comment by teichsta** [comment] 2016-01-10 19:45
duplicate of #3358

**Closed by teichsta** 2016-01-10 19:45 UTC
Labels: duplicate

**Comment by kaikreuzer** [comment] 2016-01-10 19:47
Oh, indeed. I didn't expect that issues marked critical were still open...

**Comment by teichsta** [comment] 2016-01-10 19:49
unfortunately yes … hope to fix these kind of issues very soon after 1.8 and ship as 1.8.1
