### ISSUE TITLE
Error opening rules files in openHAB Designer 1.6.2 for Mac

### ISSUE THREAD

**Issue by robertvanbregt** [openhab/openhab#2415] opened 2015-04-07 09:04 UTC
If you open a rules file in openHAB Designer 1.6.2 (and 1.6.1) for Mac, a null pointer exception is thrown.

    An error has occurred. See error log for more details.
    java.lang.NullPointerException

![nullpointerexception](https://cloud.githubusercontent.com/assets/559346/7019949/4a6ab7d8-dd15-11e4-832f-1a8bcda9a76e.png)

This is from the log file:

```
!ENTRY org.eclipse.jface 4 2 2015-04-07 10:59:15.215
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.internalFixContext(PartServiceImpl.java:380)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:341)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1029)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3047)
	at org.eclipse.ui.internal.WorkbenchPage.access$22(WorkbenchPage.java:2969)
	at org.eclipse.ui.internal.WorkbenchPage$8.run(WorkbenchPage.java:2951)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2947)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2911)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2902)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:655)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:614)
	at org.eclipse.ui.actions.OpenFileAction.openFile(OpenFileAction.java:99)
	at org.eclipse.ui.actions.OpenSystemEditorAction.run(OpenSystemEditorAction.java:99)
	at org.eclipse.ui.actions.RetargetAction.run(RetargetAction.java:221)
	at org.eclipse.ui.navigator.CommonNavigatorManager$3.open(CommonNavigatorManager.java:185)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:48)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:866)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:864)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1152)
	at org.eclipse.ui.navigator.CommonViewer.handleOpen(CommonViewer.java:462)
	at org.eclipse.jface.viewers.StructuredViewer$6.handleOpen(StructuredViewer.java:1256)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:275)
	at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:269)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:309)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4136)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1458)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1271)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3982)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3621)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.openhab.designer.ui.internal.application.Application.start(Application.java:28)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
```

Designer 1.5.1 is working fine.

See also:
<https://groups.google.com/d/msg/openhab/tagF5eX9CGs/bH23RXFqrLEJ>

**Comment by digineut** [comment] 2015-04-10 10:41
In response to @teichsta at https://groups.google.com/d/msg/openhab/tagF5eX9CGs/U1BYGa92SpYJ
> Can you confirm that the NPE occurs with any rule file or just some (which?).

Please find below the contents of my `astro.rules` file that can be opened and edited in 1.5.1 but not in 1.6.2.

```
/* astro.rules
 * Astro related rules
 */
import org.openhab.core.library.types.*
import org.openhab.core.persistence.*
import org.openhab.model.script.actions.*
import org.joda.time.*

// This timer declaration needs to be at the top of the file. Don't ask...
var Timer tDarkLights

/*
 * SunsetTimeChanged
 * This rule sets the time that it becomes too dark inside
 * This time is used to set a timer to automatically switch a group of lights on
 */
rule "SunsetTimeChanged"
when
	Item Sunset_Time changed
then
	var Integer min = 30 // the number of minutes before sunset to switch ON
	var DateTime sunset = parse("" + Sunset_Time.state)
	postUpdate(Dark_Time, "" + sunset.minusMinutes(min))
	logInfo("astro.rules", "Changed Dark_Time")
end

/*
 * Create timer at some time before sunset
 * Uses group Lights_Indoor_Sunset to switch on lights
 * 
 * Note: when system started does not work properly, since the Astro values have not been initialized before this 
 * rule is run for the first time. Instead, use trigger for received update. This usually is the case at system restart
 * and day change.
 * 
 */
	// Switch on specific group of indoor Lights
rule "DarkTimer"
when 
    Item Dark_Time received update
then

	// If a timer already exists cancel it first to avoid reschedule
	if(tDarkLights != null) {
		tDarkLights.cancel()
		logInfo("astro.rules","Timer tDarkLights cancelled") 
	}

	var DateTime dark = parse(""+Dark_Time.state)
	
	tDarkLights = createTimer(  dark    ) [|
		sendCommand(Lights_Dark, ON)
		logInfo("astro.rules","Timer tDarkLights executed") 
	]

	logInfo("astro.rules","Timer tDarkLights created for " + dark)

end

```

**Comment by teichsta** [comment] 2015-04-10 11:39
strange … works perfectly one my side :-/ Can anybody confirm?

**Comment by digineut** [comment] 2015-04-10 13:09
I have installed Java 8 (visible through System Preferences), but when I type `java -version` in a Terminal windows, I get this:
```
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```
I am running Mac OS X 10.8.5

How can I check openHAB is using the correct Java version?

**Comment by teichsta** [comment] 2015-04-11 20:22
openHAB will use the Java version being available on the path (so 1.6 in your case)

**Comment by digineut** [comment] 2015-04-12 06:30
Could the java version cause the issue?
If so, can I force OH Designer to use my Java 8 by modifying a path?

**Comment by rrobinet** [comment] 2015-04-13 10:48
Hi,
Similar problem: MAC OSX 10.9.5 , Java 8 (I did last update 8.40)
Staring the app;  first nothing happens  so I have to modify the openHAB-Designer.ini
with: 
#-Dorg.eclipse.swt.browser.DefaultType=mozilla
-Djava.awt.headless=true
Then it starts  Ok but.
Different windows management becomes rapidly a big mess
and 
while opening a rule with the rule editor the 
java.lang.NullPointerException occurs
After that  "game over" , the application is to be downline loaded again
Robert

**Comment by digineut** [comment] 2015-04-20 04:33
I have been testing the last days. Since I have installed the Java 8 **JDK** (not JRE), I am able to use Java 8 for running the Designer. Since then, I have been able to run Designer without errors. I will try a little longer and report back. But I think the issue is resolved when you use Java 8.

To use Java 8 after installing you need to:
* have Java 6 uninstalled or
* set your .bash file to point to Java 8

**Comment by leutholl** [comment] 2015-05-04 00:55
I had exactly the same problem. The only solution worked was to modify the Info.plist of the Designer and specify the 1.8.0 VM there (the ini-file doesn't take the -vm arg) - in the very end of the plist you can find the info - mine looks like this.

<key>Eclipse</key>
		<array>
			
				<string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java</string>
				
			
			<string>-keyring</string><string>~/.eclipse_keyring</string>
			<string>-showlocation</string>
			
		</array>

**Comment by steve-bate** [comment] 2015-11-22 00:59
It appears that configuring the app to run with Java 8 is the answer to this question. Closing the issue.

**Closed by steve-bate** 2015-11-22 00:59 UTC
Labels: question
