### ISSUE TITLE
z-wave: Add new Fibaro FGS221 2x1.5kw ID's to db

### ISSUE THREAD

**Issue by JWKsDad** [openhab/openhab#3117] opened 2015-09-02 00:26 UTC
I have multiple Version 2.2  Fibaro FGS221 in my network that are only recognized as
"Fibaro System [ID:3002, Type:202]".
They all partially function but do not present Parameters on Habmin.
Request this device be added to the DB.

**Comment by cdjackson** [comment] 2015-09-02 21:56
Are you absolutely sure that this is a FGS221 and not an FGS222? I’d be very surprised if it was a 221 based on the codes.

**Comment by JWKsDad** [comment] 2015-09-03 00:46
Positive, straight from the sticker FGS221-2x1.5kW 921.4MHz v2.2.

**Comment by JWKsDad** [comment] 2015-09-03 01:07
![fgs221](https://cloud.githubusercontent.com/assets/11661006/9648429/ccdd5334-522b-11e5-8f06-9b097278b675.JPG)
This is how these devices are displaying in Habmin.

**Comment by cdjackson** [comment] 2015-09-03 05:34
Please can you post the xml for the device - from the etc/Zwave/node33.xml. I wonder if it's been jmislabeled (we've seen this before)

**Comment by JWKsDad** [comment] 2015-09-03 06:16
Thanks for looking into this.

 

Regards,

Bevan

**Comment by cdjackson** [comment] 2015-10-29 20:07
Any chance of geting the file posted here?

**Comment by JCT250** [comment] 2015-11-24 07:58
Hi Chris, I have the same issue,

Any help would be appreciated

Cheers
[node6.txt](https://github.com/openhab/openhab/files/42472/node6.txt)

**Comment by JCT250** [comment] 2015-11-30 07:34
Hi Chris, 

Just wondering whether you'd had a chance to include this device in the database?

cheers
James

**Comment by alansmith2** [comment] 2015-12-02 21:43
I also have this problem, got 4 new nodes in and can't configure :( is there a way that we can change the database or force it to use the older version of the 2 x1.5kw relay switch device id?

**Comment by cdjackson** [comment] 2015-12-02 21:45
Why do you want to use an older definition - this doesn’t make sense?

**Comment by alansmith2** [comment] 2015-12-02 22:20
looking at the XML file for the new version of the node it looks like most of the configuration parameters are the same and so if I could tell it to use the old configuration then that would allow me to configure the toggle parameter on the 4 new nodes. It's interesting I didn't think that there was a new version out so not sure what other changes there are between the two different device IDs

**Comment by cdjackson** [comment] 2015-12-02 22:22
Ok, then please define exactly what is missing, and what version of the firmware you have so we can look at this. It needs to be done systematically...

**Comment by alansmith2** [comment] 2015-12-02 22:43
Hi, It seems that Fibaro have just released a new version of the firmware which has a different Device ID. http://manuals.fibaro.com/double-relay-switch/ (has the different manuals of the different versions). I can confirm when I get home tonight that the older versions are showing a different firmware version number to the new ones. When new firmware versions come out with new device id's is it normally required to add a new device to the database?

I have one of the new nodes with me at the moment though and the instructions defiantly have v1.02 on them with the sticker on the back of the box indicating firmware 2.2

**Comment by alansmith2** [comment] 2015-12-02 22:45
Thanks for all the time you put into this BTW Chris, may not be said but it is definitely appreciated. Alan

**Comment by cdjackson** [comment] 2015-12-02 22:50
Thanks. 

The system allows different configurations for different firmware versions, so we should be able to manage this ok :)

**Comment by alansmith2** [comment] 2015-12-02 22:51
OK that would be great :D is there anything else that you require from me?

**Comment by cdjackson** [comment] 2015-12-02 22:56
Just a pointer to the manual for the software version, and the type/id for the device (and the version of course).

**Comment by alansmith2** [comment] 2015-12-02 23:09
Ok awesome, the manual here http://manuals.fibaro.com/content/manuals/en/FGS-221/FGS-221-EN-A-v1.02.pdf is the same as the one in the box. In Habmin the new node shows as 

Manufacturer ID = 10f
Device ID = 3002
Device Type = 202
Version = 4
Protocol Version = 3.52
Application Version = 2.2

**Comment by JCT250** [comment] 2015-12-15 03:39
Hi Chris, 

just wondering how far off the addition to the library would be?

Cheers
James

**Comment by cdjackson** [comment] 2015-12-15 23:01
At the moment I’m working on a number of things - mostly different OH2 bindings and additions to ESH and this is taking a lot of time. This means the constant flow of requests for database entries is unfortunately growing - they all take time to add, and it normally falls on me to add them….. If you can have a look at trying to do this yourself, it would make things a lot quicker - there is an overview of the database in the HABmin2 wiki, and you can use the existing files as a starting point, and I’m more than happy to review them.  If you’re not up for the challenge :) then it will take more time - currently I’m chipping away at the requests when I fancy a “break” from the other tasks.

Of course, if anyone reading this wanted to have a go at producing database entries for some of the zwave requests, it would be a really useful support to the openHAB team :)

**Comment by alansmith2** [comment] 2015-12-16 00:20
Ok, so i'm guessing that the Zwave binding itself needs to be updated? When I look at the openHab log file (on a virtual machine running openHAB but without HABMIN installed) the device still shows up there as being unknown as such whereas the nodes running the older version of the firmware do get detected ok. Looking inside the Zwave binding JAR file I can find the XMLs under database for the device but you mentioned there was provision for different firmware versions. It doesn't look like there is any field in the XML to define applicable firmware versions and I couldn't easily locate a separate file that would map valid firmware versions to devices. It also didn't look like there was a different XML for each applicable firmware version for each device?

**Comment by cdjackson** [comment] 2015-12-16 00:31
> 
> Ok, so i'm guessing that the Zwave binding itself needs to be updated?
> 
Yes, the XML files need to be updated - these are compiled into the JAR.

> It doesn't look like there is any field in the XML to define applicable firmware versions and I couldn't easily locate a separate file that would map valid firmware versions to devices.
> 
There is - see below for the FGD211…

			<ConfigFile VersionMax="1.8">fibaro/fgd211-14.xml</ConfigFile> 
			<ConfigFile VersionMin="1.9" VersionMax="1.11">fibaro/fgd211-19.xml</ConfigFile>
			<ConfigFile VersionMin="2.1">fibaro/fgd211-21.xml</ConfigFile> 


> It also didn't look like there was a different XML for each applicable firmware version for each device?
> 
Well, there won’t be until someone creates it, but the system supports this, and you’ll find that other Fibaro devices use this (as per my example above).

**Comment by alansmith2** [comment] 2015-12-16 00:53
Right ok, starting to make more sense, looks achievable. Had gone straight to the Fibaro folder and missed the products xml file one directory up. 

Having absolutely no idea how to compile this stuff, is there other things that are dependant on these files being as is i.e do I need to open this in some sort of dev environment and then recompile or is it possible to open the XML files from within the JAR file using something like 7Zip, make the changes and then save them back in again? 

Alternatively if I cloned https://github.com/openhab/openhab/tree/master/bundles/binding/org.openhab.binding.zwave made the changes and then committed back in then would the binding be automatically rebuilt overnight or something?

**Comment by cdjackson** [comment] 2015-12-16 00:56
If you’re not happy with all the compiling etc, then just grab the FGS221 XML file from the folder, modify it as you think it should be for the version you have, then paste it into github and I’m happy to sort out the rest - just doing this would really be a big help and would be appreciated :)

**Comment by alansmith2** [comment] 2015-12-16 01:00
Yep sure, I'll create the new file for the new firmware version and can add into the products file etc and send though :)

**Comment by cdjackson** [comment] 2015-12-16 01:03
Thanks.

**Comment by JCT250** [comment] 2015-12-16 02:37
Hey Chris, one of the parameters takes a int from 0-65535 using the value as a number of milliseconds before turning off. I've had a look through some of the other config files and can see that when numbers from 0-65535 have been used that data type short has been used so am assuming that these are by default unsigned? Also in a couple of different instances the <size> flag has been set to either 1 or 2, are you able to provide a bit of clarity for how this should be determined?

Cheers

**Comment by cdjackson** [comment] 2015-12-16 02:41
The data type isn’t used, so short, or int is ok - the important thing is really the length - this needs to be correct but it’s normally in the Fibaro user manual.

What flag do you mean (i.e. that you say is set to 1 or 2)?

**Comment by JCT250** [comment] 2015-12-16 02:52
In the fgwpe.xml file for example it has 

		<Parameter>
			<Index>39</Index>
			<Type>short</Type>
			<Default>600</Default>
			<Minimum>1</Minimum>
			<Maximum>65535</Maximum>
			<Size>1</Size>

and then further down it also has

		<Parameter>
			<Index>70</Index>
			<Type>short</Type>
			<Default>65535</Default>
			<Size>2</Size>

In one of the new firmware versions for the FGS-221 you are able to set a delay in milliseconds which can be any value from 0-65535

Ill have another dig around on the Fibaro website and see if I can find anything specifying the length for this particular parameter

**Comment by JCT250** [comment] 2015-12-16 03:14
Hi Chris, changes below, have included text file with description / line number of changes made

[FGS221.zip](https://github.com/openhab/openhab/files/63511/FGS221.zip)

Thanks a lot :)

**Comment by alansmith2** [comment] 2015-12-16 03:33
Argh beat me to it. Good work picking up differences between v1.00 and v1.01. Interesting that there are no parameter changes between 1.01 and 1.02 though?

**Comment by JCT250** [comment] 2015-12-16 03:42
Not that I could see aye. I printed out the three manuals from the Fibaro website and compared them side by side and whilst 1.01 and 1.02 differed from 1.00 there didn't appear to be any changes to either the order of the parameters nor the options available for each parameter so not sure aye.

**Comment by cdjackson** [comment] 2015-12-16 12:13
It’s quite common not to change the parameters between versions - this is why we don’t have lots of different versions for all the Fibaro devices. They seem to rev the software version, change the manual, but not change parameters…

Anyway, thanks for the files - I’ll take a look at them tonight if I get a few minutes and I don’t fall asleep (I’m out in the US for a couple of days, but my timezones are in a mess :) ).

**Comment by cdjackson** [comment] 2016-01-20 22:45
Database updated 4 weeks ago - closing.

**Closed** 2016-04-07 06:06 UTC
Labels: awaiting-feedback
