### ISSUE TITLE
Add to zwave database: Qubino Flush Dimmer 0-10V

### ISSUE THREAD

**Issue by newjoerg77** [openhab/openhab#4436] opened 2016-06-03 06:47 UTC
Please add the "Qubino Flush Dimmer 0-10V" to the zwave database.
The device is new and different from the "Qubino Flush Dimmer".

Thanks a lot!
In the following the xml file for this device:
[node23.txt](https://github.com/openhab/openhab/files/297033/node23.txt)

**Comment by cdjackson** [comment] 2016-06-03 07:14
Duplicate of https://github.com/cdjackson/HABmin2/issues

**Closed by cdjackson** 2016-06-03 07:14 UTC

**Comment by watou** [comment] 2016-06-03 07:35
FYI, bad link to issue?

**Comment by cdjackson** [comment] 2016-06-03 07:57
Thanks @watou - updated the link.
