### ISSUE TITLE
harmonyhub-service in OpenHAB2 crashing

### ISSUE THREAD

**Issue by obilan** [openhab/openhab#4963] opened 2017-01-04 21:05 UTC
This repeats in the log:

2017-01-04 22:02:36.442 [WARN ] [rg.jivesoftware.smack.XMPPConnection] - Connection closed with error
java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...<![CDATA[result=19005434]]></oa></iq>... @1:649
        at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:279)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
2017-01-04 22:02:44.056 [DEBUG] [ternal.communicator.HomematicGateway] - Received new (Double) value '20.6' for 'LEQ0594920:2#ACTUAL_TEMPERATURE' from gateway with id 'ccu'
2017-01-04 22:02:44.056 [DEBUG] [ternal.communicator.HomematicGateway] - Received new (Double) value '51.0' for 'LEQ0594920:2#ACTUAL_HUMIDITY' from gateway with id 'ccu'
2017-01-04 22:02:44.057 [DEBUG] [ternal.communicator.HomematicGateway] - Received new (Double) value '20.5' for 'LEQ0594920:2#SET_TEMPERATURE' from gateway with id 'ccu'
2017-01-04 22:02:44.073 [DEBUG] [l.communicator.HomematicCommunicator] - Received new (Double) value '20.6' for DatapointConfig[address=LEQ0594920,channel=2,parameter=ACTUAL_TEMPERATURE]
2017-01-04 22:02:44.074 [DEBUG] [l.communicator.HomematicCommunicator] - Received new (Double) value '51.0' for DatapointConfig[address=LEQ0594920,channel=2,parameter=ACTUAL_HUMIDITY]
2017-01-04 22:02:44.074 [DEBUG] [l.communicator.HomematicCommunicator] - Received new (Double) value '20.5' for DatapointConfig[address=LEQ0594920,channel=2,parameter=SET_TEMPERATURE]
2017-01-04 22:02:45.118 [WARN ] [rg.jivesoftware.smack.XMPPConnection] - Connection closed with error
java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...<![CDATA[result=19005434]]></oa></iq>... @1:649
        at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:279)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
2017-01-04 22:03:04.052 [DEBUG] [l.communicator.HomematicCommunicator] - Received new (Double) value '20.6' for DatapointConfig[address=LEQ0594920,channel=1,parameter=TEMPERATURE]
2017-01-04 22:03:04.052 [DEBUG] [onverter.state.AbstractTypeConverter] - Converting (Double) value '20.6' with DecimalTypeConverter for HmDatapoint[address=LEQ0594920,channel=1,parameter=TEMPERATURE]
2017-01-04 22:03:04.053 [DEBUG] [l.communicator.HomematicCommunicator] - Received new (Integer) value '51' for DatapointConfig[address=LEQ0594920,channel=1,parameter=HUMIDITY]
2017-01-04 22:03:04.053 [DEBUG] [onverter.state.AbstractTypeConverter] - Converting (Integer) value '51' with DecimalTypeConverter for HmDatapoint[address=LEQ0594920,channel=1,parameter=HUMIDITY]
2017-01-04 22:03:04.071 [DEBUG] [ternal.communicator.HomematicGateway] - Received new (Double) value '20.6' for 'LEQ0594920:1#TEMPERATURE' from gateway with id 'ccu'
2017-01-04 22:03:04.072 [DEBUG] [ternal.communicator.HomematicGateway] - Received new (Integer) value '51' for 'LEQ0594920:1#HUMIDITY' from gateway with id 'ccu'
2017-01-04 22:03:08.419 [WARN ] [rg.jivesoftware.smack.XMPPConnection] - Connection closed with error
java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...<![CDATA[result=19005434]]></oa></iq>... @1:649
        at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:279)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]
        at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)[194:org.openhab.binding.harmonyhub:2.0.0.201701011144]

**Comment by 9037568** [comment] 2017-01-05 03:51
This appears to be:
1) using the OH2 harmonyhub binding
2) a duplicate of [this defect](https://github.com/openhab/openhab2-addons/issues/1222)

Please follow the issue in OH2.

**Closed by 9037568** 2017-01-05 03:51 UTC
