### ISSUE TITLE
Mysql persistence don't log anything and no errors

### ISSUE THREAD

**Issue by Dannikorsholm** [openhab/openhab#1934] opened 2015-01-05 21:43 UTC
I got openhab 1.5.1 installed on win 8 and all works great.

Now i got a raspberry pi with openhab 1.6 and can't get mysql to log anything.
I tried a lot of different setup in the persist file. The setup that worked on 1.5.1 don't work.

When i launch openhab start.sh the only thing about mysql i get is:  

2015-01-05 20:21:40.203 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'mysql.persist'

When i launch with debug i get this:

21:23:23.029 [INFO ] [c.internal.ModelRepositoryImpl:79   ] - Loading model 'mysql.persist'
21:24:04.321 [DEBUG] [sqlPersistenceServiceActivator:32   ] - mySQL persistence bundle has been started.
21:24:04.861 [DEBUG] [.p.internal.PersistenceManager:146  ] - Initializing mysql persistence service.
21:24:07.304 [DEBUG] [.p.m.i.MysqlPersistenceService:434  ] - mySQL configuration starting
21:24:07.317 [DEBUG] [.p.m.i.MysqlPersistenceService:359  ] - mySQL: Attempting to connect to database jdbc:mysql://127.0.0.1/Openhab

21:24:17.683 [DEBUG] [.p.m.i.MysqlPersistenceService:362  ] - mySQL: Connected to database jdbc:mysql://127.0.0.1/Openhab
21:24:17.800 [DEBUG] [.p.m.i.MysqlPersistenceService:369  ] - mySQL: Setting wait_timeout to 65 seconds.
21:24:17.867 [DEBUG] [.p.m.i.MysqlPersistenceService:495  ] - mySQL configuration complete.

I created a database for openhab and when i launch openhab it create Items/ItemId and ItemName but empty and don't logging anything..

Can someone help ???

Regards Danni.
##

**Comment by teichsta** [comment] 2015-01-06 20:25
> I created a database for openhab and when i launch openhab it create Items/ItemId and ItemName but empty and don't logging anything..

you  mean the MySQL PersistenceService didn't log anything?

Can you please provide items and persist configuration?

Thanks, Thomas E.-E.

**Comment by Dannikorsholm** [comment] 2015-01-06 21:02
Yes no log and no errors from the mysql persistence.. Only creates the two data tables..


Items:

Group All
Group Hus	(All)
Group Temp	(All)
Group Lys	(All)

/*Temperature*/

Number Temperatur_Gang		"Temperatur Gang [%.1f °C]"		<temperature>	(Temperature, Temp) { ihc="0x7CF314:30" }

Number Temperatur_Alrum		"Temperatur Alrum [%.1f °C]"		<temperature>	(Temperature, Temp) { ihc="0x6314:30" }

Number Temperatur_Sove		"Temperatur Soveværelse [%.1f °C]"	<temperature>	(Temperature, Temp) { ihc="0x82F614:30" }

Number Temperatur_Bad		"Temperatur Bad [%.1f °C]"		<temperature>	(Temperature, Temp) { ihc="0x830014:30" }

Number Temperatur_Bad2		"Fugtighed Bad [%.1f %%]"		<temperature>	(Temperature, Temp) { ihc="0x830114:30" }

Number Temperatur_Varelse1	"Temperatur Varelse vest [%.1f °C]"	<temperature>	(Temperature, Temp) { ihc="0x830A14:30" }

Number Temperatur_Varelse2	"Temperatur Varelse Ost [%.1f °C]"	<temperature>	(Temperature, Temp) { ihc="0x831414:30" }


And mysql:

// persistence strategies have a name and a definition and are referred to in the "Items" section  
Strategies {  
    everyHour : "0 0 * * * ?"  
    everyDay  : "0 0 0 * * ?"  
    every15Mins : "0 0,15,30,45 * * * ?"  
    // if no strategy is specified for an item entry below, the default list will be used  
    default = everyChange  
}  
Items {  
    Temperature* : strategy = every15Mins 
}  

I used differences setup in the mysql file but nothing Works. The mysql file Works on win 8 openhab 1.5.1.

**Comment by teichsta** [comment] 2015-01-14 16:02
hmm … is it really 1.6(.0) you've installed on your system? If yes please the latest 1.6.1 Release. Also you could try to install 1.6.1 on your Win8 machine and see if that works

**Comment by Dennis650** [comment] 2015-04-01 20:49
Hi,

no feedback on this one? Can this issue be closed?

Greetings
Dennis

**Comment by teichsta** [comment] 2015-04-01 20:58
Thanks for this update, @Dennis650. Will mark this Issue to be closed soon …

**Comment by stronk7** [comment] 2015-04-21 11:36
Hi. Just to comment that I have also experimented a "weird" behavior with the mysql persistence plugin, similar to this, especially on first runs, when all the ItemXXX tables are still not created. Curiously, once all them were there, it started to work perfectly, reacting well to connection issues and overall working ok.

Tracing down the code... I came to these 2 conclusions (although I'm afraid, I have not time right now to implement, pull request them):

1) getTable() should feed errCnt. If for any reason, you have a connection problem, then that method won't return a target table ever, so store() will return all the time, all the time without ever trying a new connection. Note that I've not looked if there are more DB operations missing the errCnt++ thing, but for sure getTable() is.

2) isConnected() is not reliable at all. I've tried here closing the connection from the server (killing the mysql connection) and it was not detected ever from the persistence client. It should include a real check of the database status (something like "SELECT 1" execution or, why not, the correct jdbc. isValid(timeout) way. 

I'm sure that with those small changes, a lot of problems reported with MySQL will, magically, disappear. Again, I'm afraid I cannot provide a patch for them.

Hope it helps, ciao :-)

PS: And thanks for OpenHAB, I'm loving it since some weeks ago together with a Razberry and some custom bindings (not using zwave form OpenHAB, but the REST APIs in both sides to keep them communicated and working together. Hope I can share them once stable enough.

**Comment by Dennis650** [comment] 2015-04-23 15:09
Hi,

i looked into the code. I would implement a getConnection Method which is used with every statement, instead of isConnected and errCnt. The getConnection Method can handle thinks like connect / isValid / reconnect.

Your point 2. or implementing a getConnection method would change the default behavior of the persistence binding, which leaves the connection disconnected if a failure occures.
So the pull request would not be accepted. See diskussion here: https://github.com/openhab/openhab/pull/2472
Losing data never makes sense i think, but the default behaviour should not be changed before OpenHab2. 

Greetings
Dennis

**Comment by stronk7** [comment] 2015-04-23 15:39
Well, I don't know much about OH2, neither about changing behaviors. My 2 points above don't propose anything but fix 2 little things that right now are not working as expected. Using the same numbers:

1) errCnt does NOT count properly. There are operations where that counter is not feed. Hence the expected behavior simply does not work.
2) isConnected() is not really looking for a working connection. I'm not proposing to reconnect, neither to introduce a change about how connections are handled. Simply it's not reliable and assumes a connection is there when it may not be the case.

Anyway, thanks. I just "suffered" the problems (specially the errCnt not being feed by getTable() ever, that I think it's a real bug. Luckily it only affects installations having tables to be created.

Once I got all them created, everything seems to be working ok (but some groups getting incorrect DB types, but that does not hurt much here for now).

Ciao, Eloy :-)

**Comment by Dennis650** [comment] 2015-04-23 15:46
Hi,
if isConnected returns false because of an invalid connection, other code will do reconnect. That will change the default behavior.
I think i will build my own mysql-persistence with getConnection method.
Greetings
Dennis

**Comment by Dennis650** [comment] 2015-04-23 16:04
Hi,

i simply can add a isValid check and increase errCnt in isConnected.

Greetings
Dennis

**Comment by teichsta** [comment] 2015-04-26 21:11
merged #2503 into master. It seems a proper "isConnected" check is open to implement. So shall we leave this issue open?

**Comment by Dennis650** [comment] 2015-04-27 20:46
Hi,

there should be a getConnection method, which gives a valid connection instead of "isConnected". The method should try a reconnect, if the connection is not valid. If no valid connection could be established, the method should throw a exception.

The errCnt and threshold functions should be deleted, it think. 

Greetings
Dennis

**Comment by stronk7** [comment] 2015-04-28 17:35
Thanks for adding the errCnt increments to getTable(), yay!

So now, at least, after errCnt failures it will try to reconnect (because isConnected() will begin to return false. Super.

I agree with Dennis (not knowing much, be warned), that surely the change to a valid check will very much, kill the need of the errCnt. So maybe, yes, it's a good idea to move that to OH2, or wherever you are planning a refactor of the mysql/sql persistence.

Ciao, and re-thanks!

**Comment by aerickson** [comment] 2016-01-31 21:47
I'm using 1.8.0 and I'm having a similar issue. OpenHab can connect to MySQL (it creates an Items table), but it never adds items or creates the other ItemsXXX tables. Any ideas?

Thanks,
Andy

**Comment by Dennis650** [comment] 2016-01-31 21:51
Hi,

you should use the forum for such questions: https://community.openhab.org

And post your mysql.persist file with you question.

Greetings
Dennis

**Comment by hmerk** [comment] 2016-11-14 21:18
Is this issue solved then and can be closed ?

**Comment by hmerk** [comment] 2016-11-20 20:57
Seems to be solved.

**Closed by hmerk** 2016-11-20 20:57 UTC
Labels: bug
