### ISSUE TITLE
UPB binding request

### ISSUE THREAD

**Issue by bbrendon** [openhab/openhab#2583] opened 2015-05-12 06:03 UTC
Binding for a UPB PIM
http://www.simply-automated.com/products/items/UMC-DB9-W_serial_interface.php

forum thread
https://groups.google.com/forum/#!topic/openhab/ouEpEkmKBz4
##

**Comment by teichsta** [comment] 2015-05-14 22:09
Would be great to find somebody volunteering to implement this … you?

**Comment by rismoney** [comment] 2015-11-30 05:11
There is an implementation here in node https://github.com/DaAwesomeP/node-upb/
Not sure where to start as I am not a Java guy.

**Comment by DaAwesomeP** [comment] 2016-02-14 23:41
I would be happy to assist. I'm interested too. I'm not a Java guy either, but the entire command generation is just basic logic. The checksum is the only tricky part. Then you just send it over serial.

**Comment by DaAwesomeP** [comment] 2016-02-14 23:46
I have a CLI version that could be used, but that might be a slightly sloppy implementation.

**Comment by DaAwesomeP** [comment] 2016-02-16 21:42
@teichsta I'm really interested in making this work. I'm sure that I can just model it off of another driver.

Here's how to protocol works (basically):

1. Commands are sent and received via serial (either USB or DB9 cable) to the computer.
2. Commands are hex with a checksum at the end. Commands can be sent multiple times and have a part that says 1 of 3, 2 of 3, etc.
3. Every device in the UPB network has a network number and ID.
4. Multiple devices linked together create a link that can be controlled all at once.
5. Devices can be controlled to turn on/off/dim/blink/turn off in x minutes at different rates. Some devices can have multiple channels, but I am yet to come across this. It could just look like two switches.
6. Links have a fewer set of commands available.
7. The commands that deal with programming the switches are done by the free UPB software and shouldn't be needed for the scope of this.
8. A device's status can be queried, but if the option is set in the UPB program, then they should broadcast their status whenever it changes.

When adding devices, there should be the following options:
 - Network
 - ID
 - Channel
 - Various repeater options
 - Name
 - Dimmable or not
 - Type (light, fan, whatever)

Should I port my library over or just make a CLI binding? Does OpenHAB already handle serial devices?

**Comment by DaAwesomeP** [comment] 2016-02-28 21:41
Anyone?

**Comment by DaAwesomeP** [comment] 2016-03-15 01:36
I'd be happy to develop this, but I just need a little guidance in the right direction or at least verification that a pull for this will be accepted. Thanks!

**Comment by rismoney** [comment] 2016-03-25 18:33
someone has opened this-
https://github.com/openhab/openhab/pull/3883

**Comment by bjhiltbrand** [comment] 2016-04-12 02:06
I don't know how many people have used homeseer in the past, but I use it with a UPB plugin (UPB Spud) that essentially takes the output from an UpStart Export and parses it to create an exact replica of the settings you have in UpStart. It's pretty slick and super easy to use. I would like to see something like that be implemented here. I don't know what I can do to help, but I'm willing to test on my network.

**Comment by DaAwesomeP** [comment] 2016-04-12 02:09
The UPStart export is a CSV file and is very parsable. Simply Automated has a PDF on how it works, but it's old and probably won't include the newer products: http://www.simply-automated.com/documents/UPStartExportFileV_5_SA.pdf

**Comment by DaAwesomeP** [comment] 2016-04-12 02:38
@bjhiltbrand Someone has already done the communication part in #3883.

If you're still interested, I have a JavaScript/NodeJS library that you can look at for reference: [DaAwesomeP/node-upb](https://github.com/DaAwesomeP/node-upb). There's also lots of useful stuff (including the command wizard and official PDFs) here: http://www.simply-automated.com/tech_specs/

**Comment by bjhiltbrand** [comment] 2016-04-12 03:06
Sounds good. I will take a look. Looking at my newly exported .UPE file from UpStart and comparing it to the document from simply automated, I came across this line;

"When reading this record, the most important thing is the file version.  Current versions of UPStart produce version 5 files."

My .UPE export indeed shows version 5, so I would venture to guess that the documentation provided by simply automated should still be relevant for the task at hand.

**Comment by bjhiltbrand** [comment] 2016-04-13 17:18
I found this updated document regarding the UPStart Export file.
[UPStart Export File Description_V5_2.pdf](https://github.com/openhab/openhab/files/217624/UPStart.Export.File.Description_V5_2.pdf)

**Comment by bracklanna** [comment] 2016-09-07 00:13
Anyone still alive / working on a UPB binding?  I don't have time or skill to work on this personally at the moment, but I am an active user of UPB devices in my home and would greatly appreciate having a usable binding.  The UPB spec & the RS232 / USB interface device interface command sets are well-documented. Let me know if I can be helpful w/ testing or debugging.

**Comment by DaAwesomeP** [comment] 2016-09-07 00:23
@bracklanna I've been using the latest JAR from https://github.com/openhab/openhab/pull/3883#issuecomment-216430180 since it was uploaded. It's working flawlessly with my Simply Automated devices and RS232 PIM.

**Comment by bracklanna** [comment] 2016-09-07 00:27
@DaAwesomeP thanks for your prompt reply. Is there any way we can get UPB listed as an official binding in the main list of bindings for OpenHAB? I don't see it there now. Having more people know about it would probably help out the development effort.

UPB seems like a very robust & therefore useful protocol. I haven't used HAI/Omnilink but my understanding is that it is kind of a kludge by comparison. UPB devices are $$$ but having them work reliably is worth it.

**Comment by DaAwesomeP** [comment] 2016-09-07 00:37
@bracklanna If #3883 is merged, then it will be in the official list. I really hope this happens soon.

To be honest I don't agree with your latter statement. UPB is not as robust as it sounds unless wiring is done 100% flawlessly in a setup. I have to press buttons sometimes 3 time to get a link or another device to turn on (there's no noise, just old and inconsistent wiring). Also, it's a dying protocol since nobody's really adopting it. Transmissions can only be sent and received one at a time, and it takes a long time to transmit and receive (you can't just press all the switches as quickly as you can). I honestly love the way they work, but I don't find them reliable. The cheaper switches (Simply Automated) physically jam easily (or at least mine do) and use the old UPB network (works fine, just older and incompatible with newer stuff). The nicer switches cost more $$$. My next installation will use some other (sadly but most likely) wireless solution.

**Comment by bracklanna** [comment] 2016-09-07 00:48
@DaAwesomeP, always appreciate having a perspective other than my own. I'm sure results do vary considerably depending on wiring configuration / quality / complexity, # UPB devices on the network. FWIW my setup so far consists of just 3 SAI (Simply Automated) 1-circuit dimmer switches. House is 1200 sq ft, 1 breaker panel w/ ~20 breakers, mix of older & newer wiring. (All of the UPB switches are on brand-new wire runs back to the panel.)

So far I have only used the RS232 interface to poll & program devices, and for some manual ON/OFF/FLASH/DIM testing. Has been 100% reliable so far, & the switches themselves in stand-alone operation also totally reliable to date. (Admittedly, that's only about 3 months.)

I do agree that the protocol's bandwidth & lack of full-duplex communication is at the bottom end of usable in the modern age. But in a world of ever-increasing RFI sources & interference I'd rather have a slow & reliable wire-line protocol than a fast-but-flaky wireless. (I would *never* use Z-wave for something like a security system, for example.)

As far as UPB being a dying protocol, that may be true, I'm not in a position to speak authoritatively. It does seem like there's a small but healthy ecosystem of competing vendors (SAI / Pulseworx) and if I'm not mistaken Leviton also makes (or perhaps just OEM's) some UPB devices.

For on-the-120V-wire signalling solutions, (aside from X10 which is beyond the pale -- waaay too flaky,) are there any other comparable alternatives to UPB in the US market?

**Comment by DaAwesomeP** [comment] 2016-09-07 00:54
> I'm sure results do vary considerably depending on wiring configuration / quality / complexity, # UPB devices on the network.

I've been using 9 or so SAI devices across multiple breakers and subpanels for several years now. I have a non-addressable/fully automatic repeater between the subpanel and main panel. The reliabilty issues are between select switches that I have set to control the load of each other. I've had lots of issues getting the SAI switches to fit in standard US boxes and jamming/spring issues with the single-rocker plates.

> But in a world of ever-increasing RFI sources & interference I'd rather have a slow & reliable wire-line protocol than a fast-but-flaky wireless.

I agree. Sadly such solutions are drying up.

> For on-the-120V-wire signalling solutions, (aside from X10 which is beyond the pale -- waaay too flaky,) are there any other comparable alternatives to UPB in the US market?

I've yet to find any alternatives.

**Comment by bracklanna** [comment] 2016-09-07 01:10
> The reliabilty issues are between select switches that I have set to control the load of each other.
If the problems are reproducible & stable that is encouraging & probably points toward a problem with a specific wire path, i.e. maybe too many branches causing reflections, or a bad / old splice somewhere. Might be worth pulling the affected devices & putting them on a test bench w/ a short run of clean wire. If the problem goes away, there you go, time for new wiring.

> I've had lots of issues getting the SAI switches to fit in standard US boxes and jamming/spring issues with the single-rocker plates.

I agree that the switches are bulky & a tight fit in standard boxes. Since I've been replacing knob&tube anyway (with 1940's era boxes) I've cut open the walls, at a minimum I install a 2-gang deep box which allows plenty of space. So far no issues with springs / jamming, admittedly these are young switches & haven't gotten more than 1000 cycles on any of them.
But I wonder if the physical problems may be related to cramming the switches into tight boxes. It may be that even a fraction of a millimeter of torsional strain on the entire case messes up the pivot / spring on the rocker.

**Comment by bbrendon** [comment] 2016-09-07 01:12
This is for discussion about software bugs and feature requests. Its not for debating the usefulness, maturity, whatever of a particular technology. Move your discussion to a proper forum.

**Comment by bracklanna** [comment] 2016-09-07 01:14
@bbrendon Right, hoops, got carried away. Apologies.

**Comment by bracklanna** [comment] 2016-09-07 01:32
@DaAwesomeP , if you are willing pls. send alternate contact info, i.e. perhaps an account on the OpenHAB forums or Google discussions if you have one, so that we can move this convo to an apporpriate place.

@bbrendon if @DaAwesomeP can cooperate, afterward I will delete this & other non-relevant posts.

**Comment by DaAwesomeP** [comment] 2016-09-07 01:52
@bracklanna Start a thread on CocoonTech Forums

**Comment by bracklanna** [comment] 2016-09-07 02:13
@DaAwesomeP  OK I started a thread there just now, pls. post your replies & I will post mine, in chronological order.

**Comment by bracklanna** [comment] 2016-09-07 03:04
@DaAwesomeP  Completed, I deleted my posts here, do same

**Comment by DaAwesomeP** [comment] 2016-09-07 03:12
@bracklanna I don't like deleting posts no matter how off topic they are, but alright.

**Comment by bracklanna** [comment] 2016-09-07 03:13
It seemed a pretty clear case of getting way off topic. Sorry, mine are gone already & not possible to restore in chronological order

**Comment by 9037568** [comment] 2016-11-10 04:36
Closed via #3883

**Closed by 9037568** 2016-11-10 04:36 UTC
Labels: enhancement, pr-submitted
