### ISSUE TITLE
Z-Wave - Unrecognized device: Popp plug switch outdoor

### ISSUE THREAD

**Issue by Alpoy** [openhab/openhab#3462] opened 2015-11-24 19:14 UTC
@cdjackson 
Hi Chris,

Could I bother you for a minute to add this device:
![popp](https://cloud.githubusercontent.com/assets/11949996/11377580/d999f086-92e6-11e5-8d5f-993848135e5c.jpg)

I think it's basically the same as the : http://www.pepper1.net/zwavedb/device/692 just the "outdoor" version.
Ref: 
http://www.popp.eu/products/actuators/wall-plug-switch/   (indoor)
http://www.popp.eu/products/actuators/wall-plug-switch-outdoor/  (outdoor)

Thanks for any help!
Alpoy

**Comment by johkin** [comment] 2015-11-26 23:33
Added PR #3471
Haven't got the hardware to test it, so please test it.

**Comment by Alpoy** [comment] 2015-11-27 08:19
Thanks @johkin 
I tried the latest z-wave addon (from cloudbees) but it doesn't recognize it, same status in habmin as I posted above.
Not that familiar with how github works but maybe I have to wait for the PR to be merged with the main code?

**Comment by johkin** [comment] 2015-11-27 08:24
Yes, the pull request has to merged before you can try it out!
I haven't got access rights to merge directly to openhab repo, so we have to wait and see if my contribution passes the QA...  :)
Sorry for being unclear!

**Comment by Alpoy** [comment] 2015-11-27 08:53
Ah I see, thanks again :)

**Comment by Alpoy** [comment] 2015-11-28 15:51
@johkin, I've tested it now and it works very well. Having some issue though with the meter functionality but it's not related to OH but the device itself. 

To make the device do metering (kwh) you have to set a Load parameter in watts to make it calculate kwh...but this makes no sense? The load (watt) will change all the time so you can't (or really shouldn't) hardcode it.

![t](https://cloud.githubusercontent.com/assets/11949996/11452654/0d896294-95f0-11e5-971f-64216373ccda.png)

**Comment by cdjackson** [comment] 2015-11-28 16:52
Can I suggest we close this issue since the device is added, and you've confirmed it's working. I would suggest starting a thread on the forum to discuss the configuration further (I have a different Popp switch, and I think it works ok).

**Closed by cdjackson** 2015-11-28 16:52 UTC
Labels: feature-request
