### ISSUE TITLE
Z-Wave wall plug "ghost switching"

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#2740] opened 2015-06-15 10:14 UTC
Hi,

I have 2 Z-Wave Fibaro Wall Plugs that have been working great for months with OpenHAB.
My controller is an Aeon Labs Z-stick.

As I said, they have been working for months with no problems.
However, in the last 2 weeks I have had 3 incidents of what I call "ghost switching". I mean, the wall plug suddenly switches off as if I had pressed the button or sent a command to switch it off.

It is an important issue because I was planning to install one of this devices in the fridge socket (to detect when the fridge loses power), but right now it seems that it is more likely that the wall plug itself fails than that mains power fails.

The "ghost switching" happened two times with one of the wall plugs, and another time with the other plug. So I would rule out the devices as the cause of the problem. 

None of them are far away from the controller. In fact, one of them is inches away from the controller, so I would also rule out distance as a cause as.

In the log, openHAB registers the switch off as if I had pressed button:

2015-06-15 07:40:40 - swWallPlug1 state updated to OFF

but I swear I haven't pressed the button or send any action through the OpenHAB interface.

I would like to discard the ghost explanation also :-)

Is it possible that is caused by the new 1.7.0-RC of OpenHAB?
It may be a coincidence, but it didn't happen to me with OpenHAB 1.6.1

Does anyone have any ideas or solutions?

**Comment by watou** [comment] 2015-06-15 10:32
I can report something vaguely similar with the Ecobee binding, where on rare occasion something in the system attempts to perform an update on an item that's bound to Ecobee.  It always fails to perform the update, but that might be a binding-specific side effect.  In any case, I have also seen "ghost updates" in a different binding.

**Comment by sercasyr** [comment] 2015-06-15 10:40
The update itself is not "ghost". The update is real because the device switches off.
The "ghost" is the command (which I haven't sent) that causes the update.

I have also checked the Fibaro parameters: overload protection is disabled, response to alarms is set to "none", and nothing that I see should allow the device to switch off without human (or OpenHAB) intervention.

However, there is no COMMAND OFF registered in the logs.
It is really as if the device had been switched off by pressing the button.

This is a real mystery for me...

**Comment by teichsta** [comment] 2015-06-17 19:02
@sercasyr since this issue is not yet reproducible i'd like to close it for now and rather discuss it on the (even more) frequented Google Group. Once the cause is narrowed down, please feel free to reopen this issue. Could you please transfer the discussion?

**Closed** 2015-06-17 19:03 UTC
Labels: question
