### ISSUE TITLE
.forEach Expression with postUpdate/sendCommand is generally broken and causes Error

### ISSUE THREAD

**Issue by c--r** [openhab/openhab#2586] opened 2015-05-12 12:13 UTC
postUpdate and sendCommand do not work in .forEach expressions anymore in Release 1.6.2 and 1.7.0 RC-1. It seems to work fine still in Release 1.6.1. 

The error can easily be observed in the demo.rules during openHAB startup (this is not a problem of the demo configuration itfself - it also breaks my own rules which worked fine before):

```
2015-05-12 13:16:34.584 [DEBUG] [m.r.internal.engine.RuleEngine] - Executing startup rule 'Initialize light states'
2015-05-12 13:16:34.677 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Initialize light states': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null
2015-05-12 13:16:34.677 [DEBUG] [m.r.internal.engine.RuleEngine] - Executing startup rule 'Initialize heating states'
2015-05-12 13:16:34.747 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Initialize heating states': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null
2015-05-12 13:16:34.748 [DEBUG] [m.r.internal.engine.RuleEngine] - Executing startup rule 'Initialize contact states'
2015-05-12 13:16:34.820 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Initialize contact states': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null
```

Extract from the demo.rules:

```
rule "Initialize light states"
	when
		System started
	then
		Lights?.members.forEach(light|
			postUpdate(light, if(Math::random > 0.7) ON else OFF)
		)
end
```

Interestingly, the following code works fine and logs the name of each light in the group:

```
rule "Initialize light states"
	when
		System started
	then
		Lights?.members.forEach(light|
			//postUpdate(light, if(Math::random > 0.7) ON else OFF)
			logInfo("demo.rules", "Light: " + light.name)
		)
end
```

**Comment by teichsta** [comment] 2015-05-16 19:24
hmm … the demo.rules works without any issues on my side. Which JDK, OS, Hardware are you using?

**Comment by dominicdesu** [comment] 2015-05-17 08:29
Seems to be the same issue as #1379 ?

**Comment by teichsta** [comment] 2015-05-17 18:55
Thanks for noticing @dominicdesu. This seems indeed being a duplicate of #1379, so i'll close this issue. @c--r please feel free to comment this (older) issue. Thanks, Thomas E.-E.

**Closed by teichsta** 2015-05-17 18:55 UTC
Labels: duplicate

**Comment by HolgerHees** [comment] 2015-12-29 09:56
Hello,

I have exactly the same issues with openhab 1.7.1

It happens for me If I run openhab with Java 8 (1.8.0_65)

If I go back to Java 7 (1.7.0_10) everthing works fine.

The only difference is that it happens not only on system startup. It happens the whole time.

Every time when I trigger the rule I can loop over all items and print the item name. The log statement works for me too. But If I try to call sendCommand or postUpdate I get the "on instance null" error.
