### ISSUE TITLE
Losing events on REST API (atmosphere)

### ISSUE THREAD

**Issue by renatoriolino** [openhab/openhab#765] opened 2014-01-20 11:34 UTC
Hi guys!

I have built myself a microcontrolled hardware to automate my home and I'm using openhab as a interface. 

The server talks with all the controllers via RS-485 and since I don't program in Java, I've made a C program to talk via rs485 with the hardware and via REST API with OpenHab.

Everything is working perfectly with OH 1.3.1 but not with OH 1.4.

With 1.4, I'm losting a lot of events (ex: I change a switch item via HABDroid my C application doesn't receive the update).

For polling the items, I'm using HTTP Header "X-Atmosphere-Transport: streaming".

Every time I lost an event, OH outputs the following on LOG:

00:01:56.844 WARN  o.a.cpr.DefaultBroadcaster[:500]- This message Entry{message=Garagem (Type=SwitchItem, State=OFF), type=ALL, future=org.atmosphere.cpr.BroadcasterFuture@33d1d377} will be lost

Let me know if you need for information.

Thanks

Renato

**Comment by teichsta** [comment] 2015-01-07 09:35
at all … we seem to still have the problem with this issue. Can anybody of the Atmosphere specialist (@digitaldan @oliver-M) please help out? /cc @jochenkluger

**Comment by jochenkluger** [comment] 2015-01-07 09:39
Hi,
I am getting this error on two testing Systems with openHAB 1.6.1 with greenT and with a custom atmosphere Client implementation. 
If some testing or log is needed, I can provide it. 
Jochen

**Comment by dominicdesu** [comment] 2015-01-10 20:31
Hi,

the `o.o.i.r.i.f.SendPageUpdateFilter[:91]- null` error is caused by a NullPointerException in [SendPageUpdateFilter.isPageUpdated()](
https://github.com/openhab/openhab/blob/6249457ff8c67ab92ac752690e433dbf0a71d99f/bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/filter/SendPageUpdateFilter.java#L107) as this cannot work:

CacheEntry entry =  ResourceStateChangeListener.getCachedEntries().get(clientId); 
  if(**entry ==null** || **entry.getData()** instanceof PageBean){
	Object firedEntity = **entry.getData()**;

I assume this should be `entry != null && entry.getData() ...` instead, but I guess it's better if @digitaldan has a look, too.

**Comment by dominicdesu** [comment] 2015-01-10 20:34
And if somebody make a pull request, would be nice to add the stacktrace to the logger output, i.e. `logger.error(e.getMessage(), e);` instead of `logger.error(e.getMessage());`. Then the error log would have been more revealing :)

**Comment by digitaldan** [comment] 2015-01-10 23:34
@dominicdesu , sorry that was my error, I added that null check to prevent the message, although its still acting the same as it did before.  I'll fix that now, but while that error message may be related to this issue, its not the cause, so I don't think avoiding it will solve anything. 
@teichsta  I'll see if I can look at this again this weekend with a set of fresh eyes.

**Comment by teichsta** [comment] 2015-01-10 23:35
thanks, that would be really great!

**Comment by teichsta** [comment] 2015-01-16 23:06
@digitaldan another weekend approaching … hopefully with fresh eyes ;-)

Thanks, Thomas E.-E.

**Comment by digitaldan** [comment] 2015-01-17 15:58
Yes, I'm looking at it again ;-) The heap dumps were very useful, thanks
for that.

**Comment by teichsta** [comment] 2015-01-19 14:29
thanks @digitaldan … i am a bit unsure whether to wait for this for 1.6.2. Any clue what the solution will look like? Any suggestions timing wise?

**Comment by digitaldan** [comment] 2015-01-19 14:31
I don't, it's tough, I run 4 android clients connected all the time as
touch screens with a fairly good size openHAB setup and do not see these
issues, there's probably a short term bandaid to aggressively clean up
stale broadcasters, long term may be OH 2.0 and something else ;-)

**Comment by jochenkluger** [comment] 2015-01-19 15:34
Hi,

if it helps, I could provide a Windows app that reproduces this behaviour in every setup I tested or I could provider the JavaScript code that is used behind the Client.

Or is there anything else I can do to help?

Jochen



________________________________
Von: Dan <notifications@github.com>
Gesendet: Montag, 19. Januar 2015 15:31
An: openhab/openhab
Cc: Jochen Kluger
Betreff: Re: [openhab] Losing events on REST API (atmosphere) (#765)

I don't, it's tough, I run 4 android clients connected all the time as
touch screens with a fairly good size openHAB setup and do not see these
issues, there's probably a short term bandaid to aggressively clean up
stale broadcasters, long term may be OH 2.0 and something else ;-)

On Mon, Jan 19, 2015 at 6:29 AM, Thomas Eichstädt-Engelen <
notifications@github.com> wrote:

> thanks @digitaldan <https://github.com/digitaldan> ... i am a bit unsure
> whether to wait for this for 1.6.2. Any clue what the solution will look
> like? Any suggestions timing wise?
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab/issues/765#issuecomment-70500394>.
>

-

**Comment by gregeva** [comment] 2015-02-15 12:16
@digitaldan - I am currently seeing this on my relatively simple OpenHAB 1.5.1 setup.  No more than 50 items, 1 minute logging using RRD, charting using default charting engine, a few rules... running on Raspberry Pi B+.  If you want to poke around, or get some logs, I would be happy to assist getting this nasty bug squashed.

**Comment by sja** [comment] 2015-02-17 09:55
Hi!

I don't see any good or minimal solution here. The best solution in my eyes would be to write an own BroadcasterCache, like the UUIDBroadcasterCache. That can can save the sent messages not just in a list but in something like a ring buffer.

For old clients, everything works like before. Clients, which reconnect with a header "X-my-last-msg-id" will be handled in a new way: They'll get the lose message because now the server now have the information, where the clients is and what he missed. The limit of this method is the size of the ring buffer. I would suggest, we use a default size of 32 messages. That should be enough for small reconnects.

If the client says, 'my last messages was nr. 1' and the oldest message in the buffer has id 100, we have to answer something like 'reload everything'. That should be solved with the status code like 416 or just 400.

Does that make sense? Is that change possible to implement for iOS and Android? I'm just a web guy. :-)

**Comment by Testato** [comment] 2015-07-16 16:36
Is this bug present on OH 1.7.0 too ?

**Comment by renatoriolino** [comment] 2015-07-16 17:03
I think so.  At least I have naver had those errors anymore.

[]'s

2015-07-16 13:36 GMT-03:00 Testato <notifications@github.com>:

**Comment by teichsta** [comment] 2015-10-16 11:40
since no real solution could be found over the past months i tend to leave this issue open and wait for the new OH2 to come (which removes Atmosphere completely). Any other suggestions?

**Comment by steve-bate** [comment] 2015-11-20 11:32
@teichsta Does this mean we should label this issue as wont-fix?

**Comment by oliver-M** [comment] 2015-11-20 18:00
I have some spare time next week. Maybe I can spent some time to find a
solution for this issue.

regards
Oliver
Am 20.11.2015 12:32 schrieb "Steve Bate" <notifications@github.com>:

**Comment by teichsta** [comment] 2016-01-02 21:36
any news @oliver-M? If not i would tend indeed to close this issue as wont-fix

**Comment by teichsta** [comment] 2016-01-07 20:40
as explained above … since the expertise for atmosphere is very rare we shouldn't too much efforts anymore. Thanks to all participating, discussing, helping on this issue!

**Closed by teichsta** 2016-01-07 20:40 UTC
Labels: bug, critical, wontfix

**Comment by paulianttila** [comment] 2016-01-08 12:06
Maybe wiki could contain "known issues" where this kind of behaviors are documented
