### ISSUE TITLE
Failed to get local hostname. 1.8.0 RPi2

### ISSUE THREAD

**Issue by brutevinch** [openhab/openhab#3767] opened 2016-01-12 06:04 UTC
Setup: RPI2, openhab 1.8.0, hostname is Home. is it bug?
Have this strange message after startup:

10:55:30,406 |-ERROR in ch.qos.logback.core.util.ContextUtil@5dd18d - Failed to get local hostname java.net.UnknownHostException: Home: Home: unknown error
	at java.net.UnknownHostException: Home: Home: unknown error
	at 	at java.net.InetAddress.getLocalHost(InetAddress.java:1484)
	at 	at ch.qos.logback.core.util.ContextUtil.getLocalHostName(ContextUtil.java:32)
	at 	at ch.qos.logback.core.util.ContextUtil.addHostNameAsProperty(ContextUtil.java:41)
	at 	at ch.qos.logback.classic.joran.action.ConfigurationAction.begin(ConfigurationAction.java:56)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:276)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:148)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:130)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:157)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:143)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:106)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:56)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:54)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at 	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:33)
	at 	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:27)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at 	at java.lang.Class.newInstance(Class.java:433)
	at 	at org.eclipse.jetty.util.log.Log.initialized(Log.java:156)
	at 	at org.eclipse.jetty.util.log.Log.getLogger(Log.java:430)
	at 	at org.eclipse.jetty.osgi.boot.internal.serverfactory.JettyServerServiceTracker.<clinit>(JettyServerServiceTracker.java:34)
	at 	at org.eclipse.jetty.osgi.boot.JettyBootstrapActivator.start(JettyBootstrapActivator.java:100)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at 	at java.security.AccessController.doPrivileged(Native Method)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at 	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at 	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at 	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at 	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.net.UnknownHostException: Home: unknown error
	at 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
	at 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
	at 	at java.net.InetAddress.getLocalHost(InetAddress.java:1479)
	at 	... 45 common frames omitted

**Comment by kaikreuzer** [comment] 2016-01-12 07:52
Looks like a duplicate of https://github.com/openhab/openhab/issues/1613. Can you confirm?

**Comment by brutevinch** [comment] 2016-01-12 08:33
@kaikreuzer Yes the same problem. But i didn't understand  is there any solution?

**Comment by kaikreuzer** [comment] 2016-01-12 08:35
I can't tell - please follow up on #1613.

**Closed by kaikreuzer** 2016-01-12 08:35 UTC
