### ISSUE TITLE
Sonos binding: restore command does not restore queue contents

### ISSUE THREAD

**Issue by johnvestberg** [openhab/openhab#1603] opened 2014-10-26 16:33 UTC
After executing the below series of commands, the "doorbell.mp3" item remains in the queue. A more expected result would be to restore the queue to its contents as per the save command.

sendCommand(Item_Sonos_Save, "ON")
sendCommand(Item_Sonos_PlayURI, "//homeserver/media/doorbell.mp3")
sendCommand(Item_Sonos_Restore, "ON")

**Comment by anordvall** [comment] 2015-06-28 20:54
I've just started trying out openHAB and have run into the same issue and would love to see it fixed. When I send the restore command the "doorbell.mp3" remains at the top of the queue and the queue being resumed is the wrong one (it's from when selecting "replace queue" in Sonos, i.e. before tracks has been e.g. manually removed from the queue)

This is kind of a showstopper for me when selecting my z-wave controller :( Any success in finding the root cause? Many thanks

**Comment by anordvall** [comment] 2015-08-20 12:31
I suspect @kgoderis is busy with other things at the moment. Is there anyone else with knowledge about the SONOS binding who can take a look at this? My wife is getting annoyed every time the queue is b0rked :)

**Comment by kgoderis** [comment] 2015-08-20 12:56
Mh…. I must admit that I seldomly use the restore command in combination with a real full playlist. Most of the time I am streaming audio from a streaming service. It might need some re-testing certainly after all the updates coming from Sonos itself

If you are fluent with a debugger you can give that a try in the meantime. Myself I will test it with my openHAB 2 environment (I do not run OH1 anymore)

Are you on the latest Sonos firmware here?

K

**Comment by anordvall** [comment] 2015-08-20 13:34
Sorry for pushing you, but many thanks for picking this up :)

I have no idea regarding debugging unfortunately :( I Believe I'm on the latest Sonos firmarware yes. At least I always choose to upgrade whenever I'm asked by Sonos. It says my version used is 5.4.

I would assume you would see the same behavior in OH2, right? Looking forward to hear your test results :) Let me know if there is anything else I can do to help out.

**Comment by anordvall** [comment] 2015-09-15 11:09
Hi Karel,

Did you manage to reproduce this issue?

Best regards,
  Andreas

**Comment by kgoderis** [comment] 2015-09-17 08:03
No not yet….

**Comment by belovictor** [comment] 2015-10-27 21:12
@kgoderis , any news?

**Comment by lauhub** [comment] 2016-01-28 18:06
I experience the same problem:
- Spotify does not allow restore,
- Restore works with TuneIn
- Restore works with Sonos playlist that includes some Spotify elements

**Comment by anordvall** [comment] 2016-01-28 18:14
The bug was reported 1 year and 3 months ago. It's super easy to reproduce. I really wish someone else could step in and help out with the SONOS binding so we can get it fixed. As a workaround I had to buy a separate Play 1 speaker dedicated for openHAB for €200, which is really money I would rather have donated to openHAB :)

**Comment by kaikreuzer** [comment] 2016-01-28 18:25
> It's super easy to reproduce.

That doesn't mean at all that it is super easy to fix - it actually is pretty complex and even 200 EUR won't get you any close to have it fixed if you would pay a professional developer to look at it...
The good news is: All of this will soon work as expected in the Sonos binding of openHAB 2. So please don't buy a Play:5, but rather donate the 500 EUR to openHAB :-)

**Comment by anordvall** [comment] 2016-01-28 18:50
> it actually is pretty complex 

Kai, come on... it's just zeros and ones! ;) Ah I didn't know the problem doesn't reproduce in openHAB 2. Does it just automagically start to work with openHAB 2 or has it actually been fixed and verified, or code completely rewritten?

I won't buy a Play 5.... where is the donate button? :)

**Comment by teichsta** [comment] 2016-01-28 23:27
www.openhab.org at the bottom right ;-)

**Comment by anordvall** [comment] 2016-01-29 08:24
Nice! Is that new? Can you please change the page to English before I hit the button? :)

**Comment by kaikreuzer** [comment] 2016-01-30 13:45
No, it has been there since many years - it seems we have hidden it well ;-)

> Can you please change the page to English before I hit the button? :)

You mean the Paypal page appears in German to you? I would have expected that it uses the locale of your Paypal website... @teichsta, could you check if we need to adjust the link to Paypal on the button?

**Comment by watou** [comment] 2016-01-30 13:48
> You mean the Paypal page appears in German to you?

Appears in German to me as well.

**Comment by steve-bate** [comment] 2016-04-09 15:36
FYI (@teichsta and @kai), the donate button is still goes to a German PayPal page from my U.S.-based browser.

**Comment by steve-bate** [comment] 2016-04-09 15:38
> has it actually been fixed and verified, or code completely rewritten

@kai, the OH1 Sonos binding has some serious problems. I'm hoping OH2 will fix it but I didn't see an answer to the previous question from @anordvall and I'm curious about it.

**Comment by kaikreuzer** [comment] 2016-04-09 16:07
The Sonos binding 2.0 is many times better and a lot of efforts have gone into it. The 1.x binding is therefore not even part of the new openHAB distro and thus I think we can close this issue as it is unlikely that anyone will put efforts into this here (as it is complex to solve as mentioned above).

**Closed by kaikreuzer** 2016-04-09 16:07 UTC
Labels: awaiting-feedback, bug
