### ISSUE TITLE
ERROR o.o.i.r.i.f.SendPageUpdateFilter[:91]- null

### ISSUE THREAD

**Issue by berndpfrommer** [openhab/openhab#1730] opened 2014-11-25 21:51 UTC
Title says it all. Is anyone else seeing these as well?

The error is generated by the filter() method
in org.openhab.io.rest.internal.filter.SendPageUpdateFilter

**Comment by kaikreuzer** [comment] 2015-01-07 08:41
Btw, this seems a duplicate of https://github.com/openhab/openhab/issues/765#issuecomment-64111601, am I right?

**Comment by teichsta** [comment] 2015-01-07 09:11
indeed, thanks for noticing! I'll close this issue for now please discuss more details in #765

**Closed** 2015-01-07 09:11 UTC
Labels: duplicate
