### ISSUE TITLE
restoreOnStartup with InfluxDB not working

### ISSUE THREAD

**Issue by nilseckert** [openhab/openhab#1225] opened 2014-07-08 10:41 UTC
When you deploy the 1.5 with the demo configuration (with restoreOnStartup) then you get a couple of exceptions on startup.

## Reproduce:
* se 1.5 distribution package
* use 1.5 demo 
* add the influxdb addon
* add attached influxdb.persist (copy of rrd)
* disable rrd.persist (rename) 

## influxdb.persist:
<pre>
// persistence strategies have a name and a definition and are referred to in the "Items" section
Strategies {
	// for rrd charts, we need a cron strategy
	everyMinute : "0 * * * * ?"
}

Items {
	DemoSwitch,NoOfLights,Window_GF_Toilet,Heating* : strategy = everyChange, everyMinute, restoreOnStartup
	
	// let's only store temperature values in rrd
	Temperature*,Weather_Chart* : strategy = everyMinute, restoreOnStartup
}
</pre>

## Log-Messages:
<pre>
12:36:48.987 DEBUG o.o.p.i.i.InfluxDBPersistenceServiceActivator[:27] - InfluxDB persistence bundle has been started.
12:36:48.996 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:93] - influxdb persistence service activated
12:36:48.996 DEBUG o.o.c.p.i.PersistenceManager[:146] - Initializing influxdb persistence service.
12:36:49.006 DEBUG o.o.c.p.i.PersistenceManager[:315] - Item 'NoOfLights' does not exist.
12:36:49.009 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:254] - got a query
12:36:49.009 ERROR o.o.p.i.i.InfluxDBPersistenceService[:257] - Configuration for influxdb not yet loaded or broken.
12:36:49.012 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:254] - got a query
12:36:49.013 ERROR o.o.p.i.i.InfluxDBPersistenceService[:257] - Configuration for influxdb not yet loaded or broken.
...
12:36:49.014 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:254] - got a query
12:36:49.014 ERROR o.o.p.i.i.InfluxDBPersistenceService[:257] - Configuration for influxdb not yet loaded or broken.
12:36:49.015 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:254] - got a query
12:36:49.016 ERROR o.o.p.i.i.InfluxDBPersistenceService[:257] - Configuration for influxdb not yet loaded or broken.
12:36:49.042 DEBUG o.o.c.p.i.PersistenceManager[:428] - Scheduled strategy influxdb.everyMinute with cron expression 0 * * * * ?
12:36:49.044 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:219] - using default url http://127.0.0.1:8086
12:36:49.044 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:225] - using default user openhab
12:36:49.044 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:237] - using default db name openhab
12:36:49.122 DEBUG o.o.p.i.i.InfluxDBPersistenceService[:120] - database status is OK
</pre>

**Comment by itheiss** [comment] 2015-01-12 06:50
@teichsta The error ist still present in openHAB 1.6 and in the the 1.7 snapshot the query is completly broken see ##1879

**Comment by theoweiss** [comment] 2015-01-16 19:42
The log messages show that the influxdb persistence service got a query() or store() request and the configuration wasn't yet read. This usually happens when openHAB starts.
I could make a PR changing the logger calls from logger.error() to logger.warn().
What do you think?

**Comment by teichsta** [comment] 2015-01-16 22:36
#1996 has been merged into master … if you agree this to be the fix, we can close this issue!

Thanks, Thomas E.-E.

**Comment by theoweiss** [comment] 2015-01-16 22:40
yes, close it!

**Comment by teichsta** [comment] 2015-01-16 22:49
Sir! Yes! Sir!

**Closed by teichsta** 2015-01-16 22:49 UTC
Labels: about-to-be-closed

**Comment by theoweiss** [comment] 2015-01-16 22:55
;-)

**Comment by fab33** [comment] 2015-01-31 21:09
Now it's a warning but it doesn't work. At startup values are not restored. Please reopen

**Comment by theoweiss** [comment] 2015-02-01 21:44
Hmm, have I missed something?
I thought it's caused by the startup behavior: the persistence service has started but not yet got it's configuration. In the meantime a query happens, which surely can't be handled.
I thought it's related to this description: https://github.com/openhab/openhab/wiki/Persistence#startup-behavior.
Any hints?

**Comment by fab33** [comment] 2015-02-02 09:26
Ok for this hint, I will try it. I didn't know about it
