### ISSUE TITLE
Netatmo binding broken in OH2 snapshot 111 (was OK in 106)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab#3937] opened 2016-01-31 09:08 UTC
Yesterday, using OH2 snapshot 106, Netatmo binding was working well.
Today, I installed OH2 snapshot 111 and netatmo binding is no more working. I get this error:
```
10:05:40.082 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 400 Bad Request
10:05:40.343 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread Netatmo Refresh Service
org.openhab.binding.netatmo.internal.NetatmoException: Could not parse JSON from URL 'https://api.netatmo.net/oauth2/token' content='grant_type=refresh_token&refresh_token=xxxxxxxxxxxxxxxxxxxxxxxxxxx&client_id=yyyyyyyyyyyyyyyyyyyyyy&client_secret=zzzzzzzzzzzzzzzzzzzzzz&scope=read_station read_camera' json='{"error":"invalid_request"}'
        at org.openhab.binding.netatmo.internal.messages.AbstractRequest.newException(AbstractRequest.java:50)[152:org.openhab.binding.netatmo:1.9.0.201601310211]
        at org.openhab.binding.netatmo.internal.authentication.RefreshTokenRequest.execute(RefreshTokenRequest.java:66)[152:org.openhab.binding.netatmo:1.9.0.201601310211]
        at org.openhab.binding.netatmo.internal.authentication.OAuthCredentials.refreshAccessToken(OAuthCredentials.java:106)[152:org.openhab.binding.netatmo:1.9.0.201601310211]
        at org.openhab.binding.netatmo.internal.NetatmoBinding.execute(NetatmoBinding.java:94)[152:org.openhab.binding.netatmo:1.9.0.201601310211]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:157)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)[153:org.openhab.core.compat1x:2.0.0.201601310204]
Caused by: org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [simple type, class org.openhab.binding.netatmo.internal.messages.NetatmoError] from JSON String; no single-String constructor/factory method (through reference chain: org.openhab.binding.netatmo.internal.authentication.RefreshTokenResponse["error"])
        at org.codehaus.jackson.map.deser.std.StdValueInstantiator._createFromStringFallbacks(StdValueInstantiator.java:379)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.codehaus.jackson.map.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:268)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromString(BeanDeserializer.java:759)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:585)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.codehaus.jackson.map.deser.SettableBeanProperty$FieldProperty.deserializeAndSet(SettableBeanProperty.java:579)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1854)[153:org.openhab.core.compat1x:2.0.0.201601310204]
        at org.openhab.binding.netatmo.internal.authentication.RefreshTokenRequest.execute(RefreshTokenRequest.java:62)[152:org.openhab.binding.netatmo:1.9.0.201601310211]
        ... 4 more
```

**Comment by robnielsen** [comment] 2016-01-31 15:05
@watou, please assign this defect to @wep4you. This is an artifact of https://github.com/openhab/openhab/pull/3841.

**Comment by robnielsen** [comment] 2016-01-31 15:34
@wep4you, I did some debugging and changing the scope from `scope=read_station` to `scope=read_station read_camera` is causing the error `{"error":"invalid_request"}`. The scope `read_camera `should only be used when there is a camera. Even though I can't test it, I assume `read_station `would be invalid if you don't have a weather station.

**Comment by watou** [comment] 2016-01-31 16:29
> @watou, please assign this defect to @wep4you.

Not able to for some reason.  Would you mind marshaling this to a fix, @robnielsen?

**Comment by robnielsen** [comment] 2016-01-31 17:05
@watou, PR submitted

**Comment by wep4you** [comment] 2016-01-31 18:14
I trink the problem is, that the request for the refresh key also must be generated with reads ration and read camera, otherwise the request will fail. I think it's no problem if you have both devices or just one, but I can't verify I have both.

**Comment by wep4you** [comment] 2016-01-31 18:21
I think we should use a new attribute in the configuration witch device or devices should be configured, so just the needed scopes get requested. I will take a look at this in about 1 week when I'm back from my vacation.

**Comment by lolodomo** [comment] 2016-01-31 18:33
For information I have both weather station and welcome camera. But i did not change my conf file. So only conf for weather is defined

**Comment by robnielsen** [comment] 2016-01-31 20:55
This should be fixed the PR https://github.com/openhab/openhab/pull/3943

**Closed** 2016-02-01 09:23 UTC
Labels: bug

**Comment by lolodomo** [comment] 2016-02-01 19:37
Still in error in OH2 snapshot 114 !

**Comment by robnielsen** [comment] 2016-02-01 20:18
OH2 snapshot 114 doesn't have the fixed version.

**Comment by lolodomo** [comment] 2016-02-01 20:44
OK. So please include this PR in the coming beta 2.

**Comment by kaikreuzer** [comment] 2016-02-01 21:40
It will be - I just triggered a new 1.9 build, which now includes this PR: https://openhab.ci.cloudbees.com/job/openHAB1-Addons/1148/
