### ISSUE TITLE
webview not working with habdroid 

### ISSUE THREAD

**Issue by renatoriolino** [openhab/openhab#2674] opened 2015-06-01 14:59 UTC
Webview is not proxying the url, but just redirecting (because of that an internal web page can not be viewed outside trhru openhab - tested with habdroid and classic interface). 

Acessing locally, the page is displayed but only the texts.  All the images are missing.

I'm using OH 1.7.0 and I use webview to render a nice TV Remote Control on OH GUI and to show some internal IP cameras too.

**Comment by teichsta** [comment] 2015-06-02 22:21
sounds like a duplicate of https://github.com/openhab/openhab.android/issues/116. Best, Thomas E.-E.

**Closed** 2015-06-02 22:21 UTC
Labels: duplicate
