### ISSUE TITLE
OpenIp Camera Binding

### ISSUE THREAD

**Issue by albertovm** [openhab/openhab#2237] opened 2015-03-05 19:10 UTC
Is there any OpenIp Camera binding?

I was looking for information about how to create it, if not exist yet, based on web interface.

http://kenneth-a-edelstein.com/FI8918W.html
http://kenneth-a-edelstein.com/FOSCAM_FI8918W_CONTROL_V5.TXT

**Comment by teichsta** [comment] 2015-03-05 20:03
duplicate of #2238

**Closed by teichsta** 2015-03-05 20:03 UTC
