### ISSUE TITLE
DateTimeType isn't thread safe

### ISSUE THREAD

**Issue by foxy82** [openhab/openhab#2945] opened 2015-07-20 06:31 UTC
DateTimeType uses a public static SimpleDateFormatter meaning that this class isn't thread safe. 

The formatter is used in lots of places in DateTimeType it is also public allowing anyone access (making this a little difficult to fix as it could be used in rules).

Proper fix would be to make these formats private and then provide formatting methods or a method to get a formatter that returns a new one each time. 

An easy fix just for the DateTimeType object would be to use a synchronized internal SimpleDateFormatter internally in DateTimeType then at least this would be safe. There would still be a risk in rules using the public formatters.

**Comment by watou** [comment] 2015-07-20 06:50
One approach to fix this would be to copy what the Android developers did with a [thread-local cache of SimpleDateFormats](https://android.googlesource.com/platform/external/apache-http/+/android-2.2_r1/src/org/apache/http/impl/cookie/DateUtils.java).  This would avoid possible blocking for access to a single shared instance.

**Comment by mrguessed** [comment] 2015-07-20 13:27
Cite: Issue #2930 Nest-Binding: Suppress occasionally failing update echo cancellations.

Linking the tickets so there's context as to why this is an issue.

**Comment by mrguessed** [comment] 2015-07-20 14:07
You can also go non-fancy, and just replace the 2x consts with Methods of the same name, and have those return a _new_ `SimpleDateFormat` object on each call.

It's low risk, low code, and isn't that slow on modern micro's

On my C1, for 1,000,000 (1M) loop executions, it takes:

Action   | Time (s)
-----------|--------
loop(Create-only) | 56
loop(Create+Parse) | 109
loop(Create+Format) | 96

If this is going to be fixed, it seems like it should be fixed for the usages _in_ this code, as well as the external usages... even if not in the most efficient manner.  Callers can also change to be more efficient when they're ready.

Either way, those public constants/functions should be decorated with Deprecated to let those callers know.

**Comment by foxy82** [comment] 2015-07-20 14:11
My suggested fix (without the deprecation yet).

```java
/**
 * Copyright (c) 2010-2015, openHAB.org and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.openhab.core.library.types;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

import org.openhab.core.types.Command;
import org.openhab.core.types.PrimitiveType;
import org.openhab.core.types.State;


public class DateTimeType implements PrimitiveType, State, Command {
	
	private static final String DATE_PATTERN_WITH_TZ = "yyyy-MM-dd'T'HH:mm:ssz";
	private static final String DATE_PATTERN = "yyyy-MM-dd'T'HH:mm:ss";

	/*
	 * SimpleDateFormat isn't thread safe however has been implemented as a public static final. To at least stop some
	 * issues I've created internal ones for the DateTimeType class to use so at least it is consistent.
	 * I've also added methods so others can use these. However I've left the public ones in as there is no telling
	 * if rules are using these.
	 */
	private final static SimpleDateFormat INTERNAL_DATE_FORMATTER_WITH_TZ = new SimpleDateFormat(DATE_PATTERN_WITH_TZ);
	private final static SimpleDateFormat INTERNAL_DATE_FORMATTER = new SimpleDateFormat(DATE_PATTERN);

	public final static SimpleDateFormat DATE_FORMATTER_WITH_TZ = new SimpleDateFormat(DATE_PATTERN_WITH_TZ);
	public final static SimpleDateFormat DATE_FORMATTER = new SimpleDateFormat(DATE_PATTERN);

	protected Calendar calendar;
	
	
	public DateTimeType() {
		this(Calendar.getInstance());
	}
	
	public DateTimeType(Calendar calendar) {
		this.calendar = calendar;
	}
	
	public DateTimeType(String calendarValue) {
		Date date = null;
		
		try {
			try {
				date = parseWithTz(calendarValue);
			}
			catch (ParseException fpe2) {
				date = parse(calendarValue);
			}
		}
		catch (ParseException fpe) {
			throw new IllegalArgumentException(calendarValue + " is not in a valid format.", fpe);
		}
		
		if (date != null) {
			calendar = Calendar.getInstance();
			calendar.setTime(date);
		}
	}
	
	
	public Calendar getCalendar() {
		return calendar;
	}
		
	public static DateTimeType valueOf(String value) {
		return new DateTimeType(value);
	}
	
	public String format(String pattern) {
		try {
			return String.format(pattern, calendar);
		} catch (NullPointerException npe) {
			return format(calendar.getTime());
		}
	}
	
	public String format(Locale locale, String pattern) {
		return String.format(locale, pattern, calendar);
	}

	@Override
	public String toString() {
		return format(calendar.getTime());
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((calendar == null) ? 0 : calendar.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DateTimeType other = (DateTimeType) obj;
		if (calendar == null) {
			if (other.calendar != null)
				return false;
		} else if (!calendar.equals(other.calendar))
			return false;
		return true;
	}
	
	public static final String format(Date time){
		synchronized (INTERNAL_DATE_FORMATTER) {
			return INTERNAL_DATE_FORMATTER.format(time);
		}
	}
	
	public static final Date parseWithTz(String toParse) throws ParseException{
		synchronized (INTERNAL_DATE_FORMATTER_WITH_TZ) {
			return INTERNAL_DATE_FORMATTER_WITH_TZ.parse(toParse);
		}
	}
	
	public static final Date parse(String toParse) throws ParseException{
		synchronized (INTERNAL_DATE_FORMATTER) {
			return INTERNAL_DATE_FORMATTER.parse(toParse);
		}
	}	

}

```

**Comment by mrguessed** [comment] 2015-07-20 16:06
@watou, can you label this bug with "bug", "esh" and "critical"?

Looks like I don't even have rudimentary permissions so I can't label.

I validated that it (at least) exists in the ESH company layer (probably elsewhere also)


Technically the Bean-style calendar interface to this class is also a t-safe issue as well.  It just might not have been exercised yet

**Comment by watou** [comment] 2015-07-20 16:39
I agree that it ought to be seen as a critical bug when thread safety issues are discovered, for all the havoc they can wreak later if not properly addressed.  I'm just not up to speed on issue labeling conventions, so lets ask @teichsta how he views this issue.

**Comment by watou** [comment] 2015-07-22 10:05
Two known issues caused by the non-thread-safe `DateTimeType.toString()` and the underlying use of the non-thread-safe `SimpleDateFormat` used across multiple threads: #2930 and #2942.  Also possibly related to issue #2508.

**Comment by teichsta** [comment] 2015-07-26 06:26
> One approach to fix this would be to copy what the Android developers did with a thread-local cache of SimpleDateFormats. This would avoid possible blocking for access to a single shared instance.

yes, but that would require Java 1.7. Since for OH1 we try to keep backward compatibility to 1.5 this would be a breaking change.

**Comment by teichsta** [comment] 2015-07-26 07:42
Thanks for analysing this issue and proposing fixes. I've created #2962 which follows @mrguessed suggestion to simply create new instances when needed which seems to me the best (quick)fix. On the long run (and for ESH, OH2) we should think probably thing about the ThreadLocal variant brought up by @watou. What do you think?

**Comment by watou** [comment] 2015-07-26 08:10
Looks like a good fix. Could switch to ThreadLocal approach in ESH and OH2 when trying to optimize performance, GC, etc.

**Comment by mrguessed** [comment] 2015-07-26 17:06
@teichsta, to be safe the Class should also _clone_ the inbound `Calendar` object (internally, in it's constructor) and also _clone_ before returning a result from `getCalendar()`.

Both of these vectors allow someone to muck with the internal `Calendar` object in a non-safe manner, since they're mutable.  Not sure if they've ever been exercised though...

**Comment by teichsta** [comment] 2015-08-26 22:06
see according ESH issue at https://bugs.eclipse.org/bugs/show_bug.cgi?id=475976

**Comment by kaikreuzer** [comment] 2015-10-26 21:38
This has not yet been merged into ESH, the referenced issue is still new and I cannot see a PR for it. Please only close this issue when such changes are sync'ed into ESH as well. This change breaks the KNX binding on OH2, that's how I noticed...

**Comment by steve-bate** [comment] 2015-11-20 11:23
@teichsta @kaikreuzer Given this appears to be fixed in OH1 and OH2 has a separate issue set, should we close this issue and open one in OH2 for syncing the changes?

**Comment by kaikreuzer** [comment] 2015-11-20 12:11
> should we close this issue 

No, for critical fixes in the core, the fix must be applied at OH1 and ESH at the same time. Actually this PR should never have been merged so far.

**Comment by kaikreuzer** [comment] 2015-12-03 10:42
@teichsta Is there any update regarding a PR for ESH?
FTR, the issue is now tracked at ESH as https://github.com/eclipse/smarthome/issues/592.

**Comment by teichsta** [comment] 2015-12-25 14:39
i've added eclipse/smarthome#782 to fix this issue …

**Comment by teichsta** [comment] 2016-01-01 22:59
since #782 has been merged meanwhile we can close this issue …

**Closed by teichsta** 2016-01-01 22:59 UTC
Labels: bug, critical, esh
