### ISSUE TITLE
OutOfMemory issues

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab#1961] opened 2015-01-11 11:18 UTC
Hello,

I am experiencing occasional lockups, which are caused by system running out of Heap space. The symptoms are that OH starts using 100% of CPU (single thread), then event processing slows down until it does not continue anymore. 

Please see my logs - the "fun" starts in the openhab.log around 3am
[logs.zip | uploaded via ZenHub](https://files.zenhub.io/54b25ba5fb4accc10a5c2f29)

Explanation for the logs:
- the zwave.log contains zwave binding information separately
- the console.log is a copy&paste of the osgi console terminal, those are things that are probably not in the logs (my logback settings does not show any of the openhab/events onto STDOUT, so my assumption is that what actually makes it there is not in the logs)

**Comment by petrklus** [comment] 2015-01-11 13:15
I would like to add that I was seeing the same issue before upgrade (running 1.5.0)

**Comment by digitaldan** [comment] 2015-01-11 16:22
Hi Petr, can you provide a heap dump by executing the following command:

jmap -dump:format=b,file=heap.bin pid

Where "pid" is the process ID of the Java process? I don't know how long it
takes to lock up, but maybe let it run for 24 hours then take a heap dump
(and post here), and then again when it does lock up.   The jmap exe should
be located in the JDK bin folder if its not on your path.

**Comment by digitaldan** [comment] 2015-01-11 16:25
One last thing, if you're worried the heap dump may contain sensitive
data you could email it to me, dan at digitaldan dot com

**Comment by teichsta** [comment] 2015-01-11 22:13
Hi,
could you provide some more details like OS, JDK, installed Add-Ons?
Thanks, Thomas E.-E.

**Comment by petrklus** [comment] 2015-01-12 09:00
Here are my bundles:
![image](https://cloud.githubusercontent.com/assets/1115667/5700676/b98b1a98-9a41-11e4-9811-1d9e41f52f6b.png)

Will run the dump as soon as it happens again - I would like to clarify, it does not seem to be happening every time I restart - only if it does, it manifests itself within 24 hours.

**Comment by digitaldan** [comment] 2015-01-12 22:52
@petrklus , as @teichsta mentioned above can you post your OS and JDK?

**Comment by petrklus** [comment] 2015-01-12 23:18
Sorry for the delay!

OS: Ubuntu 14.04 LTS
Java info:
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) Client VM (build 24.60-b09, mixed mode)
CPU: ARMv7 Processor rev 0 (v7l)

**Comment by zacofany** [comment] 2015-01-13 10:23
Yes, I'm experiencing this too with OH 1.6.1. I tried to reinstall and reconfigure OH and java (tried both 1.7 and 1.8 version) many times on my Banana PI (tried Bananian, Raspbian and Lubuntu) and I was always getting out of Heap Space after few hours. Last weekend I discovered that in my case this is strictly dependent on using Habdroid. Since I stopped to use habdroid on my (3 different) devices it looks like OH remains very stable. It looks like that it doesn't matter on which hardware Habdroid is running. Once it is connected to OH it makes that openhab starts to generate some errors and at the very end we get out of Heap Space. Also I see that Habdroid version available in Google Play is pretty old.
If  I can help you somehow to fix this issue please let me know what I should provide to you.

**Comment by petrklus** [comment] 2015-01-14 14:34
@zacofany True, I do experience the issue more often when using Habdroid - will fire a few instances to see what happens! Which version of Java are you using?

@teichsta How does my OS/JDK look to you, is there anything that is known to cause problems?

**Comment by teichsta** [comment] 2015-01-14 15:25
> It looks like that it doesn't matter on which hardware Habdroid is running.

is it really HABDroid or does this happen when using GreenT or iOS as well? If yes, than it  could be related to the Atmosphere issue #765 which also came along with an OOM.

**Comment by zacofany** [comment] 2015-01-14 19:50
Hi. Here are some details regarding my configuration:
mainboard - Banana PI
system - Bananian 15.01 r01

root@galactica ~ # inxi -Fx
System:    Host: galactica Kernel: 3.4.104+ armv7l (32 bit gcc: 4.8.2) Console: tty 0
           Distro: Debian GNU/Linux 7
Machine:   No /sys/class/dmi; using dmidecode: dmidecode is not installed.
CPU:       Dual core ARMv7 Processor rev 4 (v7l) (-MCP-) (ARM)bmips: 4008
           clock speeds: max: 1008 MHz 1: 1008 MHz 2: 1008 MHz
Graphics:  Card: Failed to Detect Video Card!
           Display Server: N/A driver: N/A
           tty size: 91x49 Advanced Data: N/A for root out of X
Audio:     Card sunxi-CODEC driver: sunxi-CODEC Sound: ALSA v: 1.0.25
Network:   Card: Failed to Detect Network Card!
Drives:    HDD Total Size: 1000.2GB (21.5% used)
           ID-1: /dev/sda model: ST1000LM014 size: 1000.2GB
Partition: ID-1: / size: 15G used: 3.1G (23%) fs: ext4 dev: /dev/root
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   None detected - is lm-sensors installed and configured?
Info:      Processes: 73 Uptime: 4 days Memory: 196.6/970.5MB
           Init: SysVinit runlevel: 2 Gcc sys: N/A
           Client: Shell (zsh 4.3.17) inxi: 2.2.16

root@galactica ~ # java -version
java version "1.8.0_06"
Java(TM) SE Runtime Environment (build 1.8.0_06-b23)
Java HotSpot(TM) Client VM (build 25.6-b23, mixed mode)

I will try to provide some logs soon.

**Comment by zacofany** [comment] 2015-01-14 22:00
OK here is some more info. Openhab.log attached.
@teichsta I dont't know if this is the same issue as Atmosphere issue #765 .
Also errors starts when I start Habdroids.
In terms of greent I have the other issue which you can see in my log from:
2015-01-14 20:52:03.136 [ERROR] [o.i.r.i.f.SendPageUpdateFilter] - null (greent started)
to
2015-01-14 20:52:29.382 [ERROR] [o.i.r.i.f.SendPageUpdateFilter] - null (greent stopped)

I started Habdroids on my 3 devices and the first ERR message is on:
2015-01-14 20:53:31.343 [ERROR] [.r.i.filter.PollingDelayFilter] - null

[openhab_outofheap.log | uploaded via ZenHub](https://files.zenhub.io/54b6e392517fc0d32175f657)

[top.screen | uploaded via ZenHub](https://files.zenhub.io/54b6e472517fc0d32175f661)

**Comment by digitaldan** [comment] 2015-01-15 21:52
@zacofany, was this your whole log file?  Did your system startup at 2015-01-14 20:23:59.795 and then throw the OOM error an hour later at 2015-01-14 21:31:49.625 ?  Thats a very aggressive memory issue.  Can you try getting a heap dump as mentioned in a previous comment?

**Comment by zacofany** [comment] 2015-01-16 00:30
@digitaldan Yes, unfortunately that's the whole log file. I will try to provide you new log and heap dump as soon as possible. However this would be the first time for me to do heap dump. At what point should I launch command 
jmap -F -dump:format=b,file=heap.bin pid ? How long does it take?

**Comment by petrklus** [comment] 2015-01-16 08:52
@digitaldan Happened again! here are my logs + heap dump:

http://cnktmp.s3.amazonaws.com/petr/20150116_logs_with_heap.zip

**Comment by zacofany** [comment] 2015-01-16 20:08
Here is new log together with heap dump.

[openhab.log | uploaded via ZenHub](https://files.zenhub.io/54b96ee2d5af864b074d4e9c)

[heap.zip | uploaded via ZenHub](https://files.zenhub.io/54b96f52d5af864b074d4e9f)

**Comment by digitaldan** [comment] 2015-01-19 14:22
Thanks all, I have enough to go on, there is definitely a leak in the broadcaster class, I'm going back through the binding to see what I can do.  If I need more logging I will let you know.

**Comment by zacofany** [comment] 2015-01-19 14:41
Thanks for the info. If you need anything more please let us know. I can even provide you remote access to my system if it is necessary.

**Comment by petrklus** [comment] 2015-01-19 14:46
Which binding is the leak in? Just curious..

**Comment by digitaldan** [comment] 2015-01-19 14:47
This would be the io.rest addon

**Comment by petrklus** [comment] 2015-01-19 15:51
@digitaldan Is it somehow specific to a mode of communication? (WebSocket, etc.) The reason I am asking is that I am having almost constantly open the standard web interface (not GreenT) on multiple machines.. and it seems to be just fine!

Keep us updated please on the progress, would like to have my tablets running again!

**Comment by digitaldan** [comment] 2015-01-19 17:15
What version of the android client is everyone on?  Could you all please post a version number?

**Comment by petrklus** [comment] 2015-01-19 17:22
HABDroid version: 1.5.1.1 (from Play store)

**Comment by digitaldan** [comment] 2015-01-19 19:32
@zacofany  and @petrklus  could you start OH using the debug script (start_debug.sh)? I only need an hour or so worth of those logs while you have android clients up.  I'm hoping they show a abnormal amount of http traffic.

**Comment by zacofany** [comment] 2015-01-19 21:48
@digitaldan I used cloudbees repository to install openhab. I need to download OH package to run start_debug.sh. Or is there any other solution for running openhab service in debug mode?

**Comment by petrklus** [comment] 2015-01-20 12:05
@digitaldan on it, just started with DEBUG. I think the other factor in my case are sensors that are pushing approx. 1 update / second via REST interface.

Do you need it to freeze again or is a snapshot after couple of hours fine?

**Comment by teichsta** [comment] 2015-01-20 12:30
> I used cloudbees repository to install openhab. I need to download OH package to run start_debug.sh.

you'll find the start_debug.sh script within the distribution-runtime archive.

Best, Thomas E.-E.

**Comment by zacofany** [comment] 2015-01-20 21:22
Hi. Here it is. Do you need heap dump too?

[2015_01_20.request.log | uploaded via ZenHub](https://files.zenhub.io/54bec717ea33564f0cc04899)

[events.log | uploaded via ZenHub](https://files.zenhub.io/54bec71fea33564f0cc0489a)

[openhab.log | uploaded via ZenHub](https://files.zenhub.io/54bec71fea33564f0cc0489b)

**Comment by zacofany** [comment] 2015-01-21 19:23
Here is another debug log, which is a little bit larger than the previous one ;-) I turned OH on in the night without any habdroid connected. I started Habdroid in the morning at about 8:45 I believe.

[openhab.log | uploaded via ZenHub](https://files.zenhub.io/54bff9cbea33564f0cc053f6)

Also all files together with heap dump file you can find here
[oom.zip | uploaded via ZenHub](https://files.zenhub.io/54bffb93ea33564f0cc05418)

**Comment by digitaldan** [comment] 2015-01-21 23:33
@zacofany , Thanks that's very very helpful, I'm going to set some time aside on Friday to really look at this. 
@petrklus , Just letting it run for a few hours with you android device up should be fine, thanks.

**Comment by petrklus** [comment] 2015-01-22 09:02
Hello!

Tried with Oracle's java8, same result! However, the process crashed instead of locking up, so I could not perform a core dump.

Here is what I saw in the logs:

    JDWP exit error JVMTI_ERROR_OUT_OF_MEMORY(110): loaded classes [classTrack.c:184]
    FATAL ERROR in native method: JDWP loaded classes, jvmtiError=JVMTI_ERROR_OUT_OF_MEMORY(110)

[logs_20150122.zip | uploaded via ZenHub](https://files.zenhub.io/54c0bbabea33564f0cc058a0)

**Comment by digitaldan** [comment] 2015-01-22 16:00
@petrklus Thanks for the log, very helpful.  You have a very chatty system ;-)

**Comment by digitaldan** [comment] 2015-01-24 16:50
@zacofany that last heap dump did not load for me, my tool complained about it maybe being truncated, could you send another once the OOM error occurs?  The first dump you posted did not show any memory issues, so I just want to make sure this is really the problem in your case.

@petrklus , there is an enormous build up of messages in a single broadcast queue, which was surprising to me, I'm still trying to figure out how all these page beans are backing up.  It looks like your system is very busy, can you describe those parts of the system?  How are you updating items from external systems?  Besides the android client, how does your setup use the rest interface ( and how and how often).  Thanks!

**Comment by zacofany** [comment] 2015-01-24 18:47
@digitaldan OK, I will try again, however as I can see now, the last log does not contain all data which I've seen on my screen. Strange. If it fail again with logging then I will get log directly from the screen. Regarding heap dump.. I have no idea why its broken.

**Comment by zacofany** [comment] 2015-01-25 00:11
Hi. Below you can find logs. I tried to get heap dump but I've got some exception. I just try to get it again.

[openhab.log | uploaded via ZenHub](https://files.zenhub.io/54c43391ea33564f0cc06fbe)

[events.log | uploaded via ZenHub](https://files.zenhub.io/54c433a4ea33564f0cc06fbf)

[2015_01_24.request.log | uploaded via ZenHub](https://files.zenhub.io/54c433b5ea33564f0cc06fc0)

**Comment by zacofany** [comment] 2015-01-25 10:03
Unfortunately It won,t work... so probably it wil be truncated again..

Attaching to process ID 11645, please wait...
Debugger attached successfully.
Client compiler detected.
JVM version is 25.33-b05
Dumping heap to heap.bin ...
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at sun.tools.jmap.JMap.runTool(JMap.java:201)
        at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.utilities.AssertionFailure: can not get class data for sun/net/ExtendedOptionsImpl$$Lambda$10xa2a9ac18
        at sun.jvm.hotspot.utilities.Assert.that(Assert.java:32)
        at sun.jvm.hotspot.utilities.HeapHprofBinWriter.writeInstance(HeapHprofBinWriter.java:803)
        at sun.jvm.hotspot.utilities.AbstractHeapGraphWriter$1.doObj(AbstractHeapGraphWriter.java:95)
        at sun.jvm.hotspot.oops.ObjectHeap.iterateLiveRegions(ObjectHeap.java:353)
        at sun.jvm.hotspot.oops.ObjectHeap.iterate(ObjectHeap.java:171)
        at sun.jvm.hotspot.utilities.AbstractHeapGraphWriter.write(AbstractHeapGraphWriter.java:51)
        at sun.jvm.hotspot.utilities.HeapHprofBinWriter.write(HeapHprofBinWriter.java:433)
        at sun.jvm.hotspot.tools.HeapDumper.run(HeapDumper.java:62)
        at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.HeapDumper.main(HeapDumper.java:83)
        ... 6 more
jmap -F -dump:format=b,file=heap.bin 11645  6077.59s user 446.10s system 99% cpu 1:48:50.00 total

[heap.zip | uploaded via ZenHub](https://files.zenhub.io/54c4bf3fea33564f0cc07103)

**Comment by zacofany** [comment] 2015-01-25 13:46
Here is another one. Hopefully heap dump is readable and contains useful data.
[OOM#5.zip | uploaded via ZenHub](https://files.zenhub.io/54c4f39dea33564f0cc07179)

**Comment by digitaldan** [comment] 2015-01-26 14:51
@zacofany , thanks that one did work.  It shows two areas of memory issues, both about equal in memory usage, one is the same as @petrklus , the other is a buildup in the UUIDBroadcaster cache, which has also been an issue before.  I'll let you know of I need any more info.

**Comment by petrklus** [comment] 2015-01-26 14:59
@digitaldan Just to shed a bit more light on the problem - just came back from a weekend away, the system running for 4 days (no Android clients running). All seems to be fine.

Yes, I am indeed updating the system from external sources, all via REST interface. The infrequent updates are calls from switches and other input devices that are using gateways different from the main OH install, the frequent updates constitute sensor data from the moisture sensors outside. They are pushing the information every few seconds, so the system does seem a bit chatty. 

For the frequent updated values, the client that is pushing the messages is this: https://github.com/petrklus/arduino-http/blob/master/main.py

There are few other systems integrated with the main OH install but they are pulling the information instead of pushing them via REST.

Is that helpful? Is there any more information you need?

**Comment by digitaldan** [comment] 2015-01-26 15:24
@petrklus that is helpful, could you describe the how the devices are pulling the rest information?  The reason I ask is that from the memory dump it looks like a huge amount of messages are sitting in a REST broadcast queue waiting to be read by a client, I'm trying to figure this out as I was unaware there was another queue other then this UUIDCache class we use to hold messages between requests from our clients.  How this relates to the android client is not clear yet.

**Comment by petrklus** [comment] 2015-01-26 15:31
@digitaldan I meant that the other devices are being pulled by OH, using the HTTP binding mainly, with some subsequent conversion in javascript. 

Would it be helpful to send you a copy of all my items & configurations?

**Comment by petrklus** [comment] 2015-01-29 09:37
@digitaldan Is there any more information I could provide? Would it be helpful to get a heap dump of OH running for a few days without the android clients? Is there anything further I could help with?

**Comment by digitaldan** [comment] 2015-01-29 14:31
Thanks, but I have enough to go on.  I have setup a simple demo environment
with rules that update items every second, so far I have had the OOM issue
happen once, but not every time, strange.  I can see the problem, for some
reason the BroadcasterCache starts to allow lots of items and pagebeans to
backup for  active sessions (uuid).  I had thought this was fixed with a
small filter I put in place to ensure the cache only contained one item at
most, the current version of the sitemaps (or piece of it), but obviously
thats not the case.  So the short answer it I'm still looking ;-)

**Comment by petrklus** [comment] 2015-01-29 14:43
Thanks for the update! Let me know if you find anything that could help..
also, you've mentioned that it could be two separate memory leaks - is this
still the case? (just curious)

**Comment by petrklus** [comment] 2015-02-05 10:30
@digitaldan Hello! Just checking in again.. without Android clients running, my system is still fine after more than a week. I occasionally launch my phone app to switch a light on/off but I do not keep it open.

Unfortunately, one of my use cases is having an android tablet mounted as a control for headless Volumio music player.. which is not possible at the moment. Is there any other way I could help out with?

**Comment by digitaldan** [comment] 2015-02-05 21:13
I have been on the road all week and have not found time to focus on it.
The good news is that I can reproduce it all the time , I have an idea for
a fix, I'm hoping to play with it this weekend when I'm back.

Sent from my mobile.

On Feb 5, 2015, at 3:31 AM, Petr Klus <notifications@github.com> wrote:

@digitaldan <https://github.com/digitaldan> Hello! Just checking in again..
without Android clients running, my system is still fine after more than a
week. I occasionally launch my phone app to switch a light on/off but I do
not keep it open.

Unfortunately, one of my use cases is having an android tablet mounted as a
control for headless Volumio music player.. which is not possible at the
moment. Is there any other way I could help out with?

—
Reply to this email directly or view it on GitHub
<https://github.com/openhab/openhab/issues/1961#issuecomment-73025336>.

**Comment by teichsta** [comment] 2015-02-05 22:31
Thanks @digitaldan appreciate your help!

**Comment by digitaldan** [comment] 2015-02-08 16:41
I see whats happening here, there was a change made to the android client, https://github.com/openhab/openhab.android/commit/44de4f44f09a7a952618b314c80237229bedbdcd . The comment says "Changed polling cycle to alternate long polling/regular requests. Improves working with current buggy Atmosphere in openHAB" .  This is effectively causing a new atmosphere session to be created every other request.  Every session starts to build up a cache of changed objects which only gets cleaned up after our default timeout (i think), on many systems I don't think this is fast enough and it runs out of memory.  Let me open a ticket up with @belovictor and see if we can work something out.

**Comment by petrklus** [comment] 2015-02-08 16:52
that makes sense! However, just a philosophical point here - is this that
leaves OH susceptible to an easy DOS attack? Or does the functionality need
to work like this?

Also, having no idea how Atmosphere works but is there any way to define
some kind of a FIFO fixed maximum size cache?

Thank you VERY much for looking into this!

**Comment by digitaldan** [comment] 2015-02-08 16:57
Both are good points, to the first one, if you are using username/password
authentication then no, I don't think this is an issue (if you don't use
auth to the outside world, you have bigger issues then this ;-)  To your
second point, yes, but its not working as it should ;-).  Atmosphere is a
complicated framework, and our implementation  is complicated on top of
that.  Its has not been easy to make things work how we want it to.

**Comment by sja** [comment] 2015-02-20 08:52
Hi!
New fresh air from my side to this issue, after I investigated in #765:
By default, Atmosphere 2.0.x has two unlimited (!) threadpools for message processing. In their [speed optimization wiki page](https://github.com/Atmosphere/atmosphere/wiki/Configuring-Atmosphere-for-Performance) on github the author suggests to limit this. I made a [branch for this](https://github.com/innoq/openhab/tree/atmosphere-limit-threadpool). Maybe that will help a bit.

As @petrklus mentioned, he has no problems on updating items from his sensors, which is a POST request. But that means many update events on the event bus, which are getting buffered in the UUIDBroadcasterCache for every connection. That problem will increase, if a sitemap contains a lot of those items because HABdroid will subscribe with long-polling to all changes of this sitemap page. If HABdroid won't use the UUID correctly as a workaround for #765, the Broadcaster will explode. :-) Does that make sense, @digitaldan ?

@digitaldan Indeed, we have a very complicated setup on top of atmosphere! With many try/catches and logging stuff on every request. I hope, my PR will remove a bit of this ovehead.

**Comment by digitaldan** [comment] 2015-02-22 00:11
@sja your timing is once again great, I am literally sitting here in front of a few terminals watching threads grow out of control and beating my head against the table ;-)   Since I have my chatty test system up, I will go ahead and try this out!

**Comment by digitaldan** [comment] 2015-02-23 02:31
Still testing this, there still seems to be an ever growing amount of threads being produced, I'm on the road for a few days but I will continue to play with this. thanks again @sja !

**Comment by sja** [comment] 2015-02-23 10:29
@digitaldan Just to be sure: You've seen my [commit](https://github.com/innoq/openhab/commit/ec1a47b02233b809a3c6d22809a7c64d141dfe26) to limit the thread pool? This is not part of the PR for Atmosphere 2.2.

**Comment by digitaldan** [comment] 2015-02-23 14:20
Yes, I combined the two for testing.

Sent from my mobile.

On Feb 23, 2015, at 3:29 AM, Sebastian Janzen <notifications@github.com>
wrote:

@digitaldan <https://github.com/digitaldan> Just to be sure: You've seen my
commit
<https://github.com/innoq/openhab/commit/ec1a47b02233b809a3c6d22809a7c64d141dfe26>
to limit the thread pool? This is not part of the PR for Atmosphere 2.2.

—
Reply to this email directly or view it on GitHub
<https://github.com/openhab/openhab/issues/1961#issuecomment-75519355>.

**Comment by digitaldan** [comment] 2015-03-01 12:44
So I think I have found the issue(s), we have a class that delays the delivery of messages to long polling clients by a few hundred milliseconds in order to group changes into a single message.  This was creating a new thread pool every time it was called, under light traffic this was not much of an issue, but on a chatty system it would hit some thread contention/locking  point and the thread creation would grow out of control very quickly.  

The second fix is in the Android client, i'll ping @belovictor and see if he he can get that merged.

The third fix was to manage the Atmosphere cache to specifically hold only a single PageBean for sitemaps requests. 

@sja I left out your commit to limit the thread pool on this PR, i was trying to keep my changes related to solving the specific issue listed above.  I think it would be great for you to do a PR on that separately as it can only help our situation.

**Comment by sja** [comment] 2015-03-01 20:56
Awesome, Dan! That sounds very reasonable. 
I'll do a PR tomorrow. 

Von meinem Telefon gesendet

**Comment by petrklus** [comment] 2015-05-13 12:04
Is this still an issue with the latest buildt?

**Comment by petrklus** [comment] 2015-06-29 14:11
... any updates?

**Comment by sja** [comment] 2015-06-30 06:17
No updates from my side. Is there still an issue with this?

**Comment by digitaldan** [comment] 2015-06-30 14:10
I have not heard any feedback one way or another.

**Comment by zacofany** [comment] 2015-06-30 15:38
Hi, I will check if this issue still exist in my case and confirm till the end of the week. Cheers.

**Comment by zacofany** [comment] 2015-07-07 12:48
Hi. I've checked it with the current build in my environment and it seems that it works flawlessly right now. Thanks!

**Comment by teichsta** [comment] 2015-07-07 12:50
it seems that #2213 solved this issue …

**Closed by teichsta** 2015-07-07 12:50 UTC
Labels: bug
