### ISSUE TITLE
[MPD] notifications not respecting player-id

### ISSUE THREAD

**Issue by mczerski** [openhab/openhab#4708] opened 2016-10-16 13:00 UTC
If I configure two mpd player ids in openhab.cfg like this:
mpd:kitchen.host=192.168.0.9 
mpd:kitchen.port=6600 
mpd:livingroom.host=127.0.0.1
mpd:livingroom.port=6600

than create two items to reflect current song title:
String livingroom_currentttrack "ᐅ[%s]" {mpd="TITLE:livingroom:tracktitle"}
String kitchen_currentttrack "ᐅ[%s]" {mpd="TITLE:kitchen:tracktitle"}

And then when i change song on one player, both items are updated with the same value.
and it doesn't event matter what is the player id in the item binding, it could be id that does not exist in config, still the same behavior.

in debug log i get:
[DEBUG] [inding.mpd.internal.MpdBinding:450  ] - Updated title: livingroom_currentttrack Nie Wyra?am Zgody
[DEBUG] [inding.mpd.internal.MpdBinding:450  ] - Updated title: kitchen_currentttrack Nie Wyra?am Zgody

the same behaviour is with the PERCENT (volume) command.

**Comment by 9037568** [comment] 2016-10-16 20:15
Going to assume this is a defect unless someone more knowledgable of MPD says otherwise...

**Comment by mczerski** [comment] 2016-10-16 20:30
well, I just looked in the code, and I believe that the relevant part is in file:
bundles/binding/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/MpdGenericBindingProvider.java
in method getItemNamesByPlayerAndPlayerCommand.
there is couple of if's for PERCENT, TITLE, ARTIST, NUMBER and "other" commands, and only "other" commands check for playerId. The code looks like written during a hackathon so can't really tell if this is what the author wanted ...

**Comment by 9037568** [comment] 2016-10-17 01:15
I noticed that block. Took way longer than expected to set up MPD and get it minimally working.

Found a few other issues with the binding along the way...

**Comment by stefanroellin** [comment] 2016-10-17 19:22
Can you try the following jar and report whether it solves your problems?

[mpd.zip](https://github.com/openhab/openhab/files/534485/mpd.zip)

See branch: https://github.com/stefanroellin/openhab/tree/mpd-use-javampd-6

**Comment by mczerski** [comment] 2016-10-17 19:56
that works great, thanks !

**Comment by mczerski** [comment] 2016-10-19 16:53
there are some problems with connection to the mpd server. after a while my openhab instance is not receiving notifications from the mpd server, but controls are still working.

**Comment by stefanroellin** [comment] 2016-10-19 18:17
This is a duplicate of issue #3060

**Comment by stefanroellin** [comment] 2016-10-19 18:40
Thanks for the feedback. I will try to reproduce the problem.

**Comment by 9037568** [comment] 2016-10-20 03:00
Fixed by PR #4713

**Closed by 9037568** 2016-10-20 03:00 UTC
Labels: bug
