### ISSUE TITLE
MapDB Snapshot not working.

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab#3197] opened 2015-09-22 19:51 UTC
I tried the current snapshot from the MapDB persistence. There were no calls in the Debug trace.
After switching back to 1.7.1 everything works fine again. There were no other changes made.
This could be due to #2661 .

**Comment by kaikreuzer** [comment] 2015-09-22 19:53
Did you test @teichsta suggested fix #3179?

**Comment by spacemanspiff2007** [comment] 2015-09-22 19:55
I don't have the IDE on this computer. Sorry.
So I just tried the build from cloudbees.

**Comment by kaikreuzer** [comment] 2015-09-22 19:57
Then it is clear that it is not working - closing this issue as a duplicate of #2661.

**Closed by kaikreuzer** 2015-09-22 19:57 UTC

**Comment by watou** [comment] 2015-09-22 21:23
PR #3179 hasn't been merged yet, so the nightly cloudbees build would not contain it.

**Comment by spacemanspiff2007** [comment] 2015-09-23 11:51
Is ist possible to write something in the changelog (or something similiar) so other people won't run into the same problem?

**Comment by kaikreuzer** [comment] 2015-09-23 15:56
Of course, it is the issue tracker and on https://github.com/openhab/openhab/issues?q=is%3Aopen+is%3Aissue+label%3Acritical+label%3Abug you will come across #2661.
Note that snapshot builds are meant for developers, not users. It is work in progress and it happens that things break there.
