### ISSUE TITLE
iOS app - cant scroll down when 2 or more Webview items exists

### ISSUE THREAD

**Issue by agsochi** [openhab/openhab#2932] opened 2015-07-17 20:41 UTC
Site map:
Webview url="http://goolge.com" height=18
Webview url="http://goolge.com" height=5

I cant scroll down to view second Webview item.

**Comment by belovictor** [comment] 2015-10-27 20:48
Duplicate of https://github.com/openhab/openhab.ios/issues/50
Already fixed.

**Closed by belovictor** 2015-10-27 20:48 UTC
