### ISSUE TITLE
Homematic binding: timeout on CCU 1 connection when using too many (~40) devices

### ISSUE THREAD

**Issue by DocZoid** [openhab/openhab#2686] opened 2015-06-03 17:14 UTC
The CCU 1 is too slow to answer the request in-time of the given 5000ms timeout when too many devices are attached.

I tested it successfully by increasing the timeout, but this should be made configurable for those who have environments where a faster timeout is needed. The default should then be increased from 5000ms to 10000ms, to avoid malfunction with CCU1.

I changed the timeout values in CcuClient.start as well as in BinRpcClient.sendMessage, but I think only the latter one is problematic.

I can add debug logs if necessary.

**Comment by teichsta** [comment] 2015-06-07 16:28
sounds reasonable … what do you think @gerrieg?

**Comment by gerrieg** [comment] 2015-06-07 17:42
the 5000ms are only to get a connection, the timeout for waiting for data is 30000ms. It wonders me that getting only a connection is so slow. Sending/receiving events is fast?

I think the problem is while fetching the metadata from the CCU. 

Can you please switch the binding to TRACE logging and post only the timestamps for:
1.) 'Loading Homematic datapoints'
2.) 'Finished loading xxx Homematic datapoints'
3.) 'TclRegaScript: ...'
4.) 'Result TclRegaScript: ...'

I don't think it is necessary to make the connection timeout configurable, i can increase it to 10000ms if that works for you. It's only necessary to change the timeout in CcuClient.start.

**Comment by DocZoid** [comment] 2015-06-07 19:10
Correct, sorry for being unprecise: sending and receiving is fast, only the startup fails with a timeout.

Here are all logs you requested (I guess I can omit the rest of the rega scripts):

2015-06-07 20:42:11.583 INFO  o.o.b.h.i.c.StateHolder[:83]- Loading Homematic datapoints
2015-06-07 20:42:11.585 TRACE o.o.b.h.i.c.client.CcuClient[:303]- TclRegaScript: string dev_id;
2015-06-07 20:42:23.044 TRACE o.o.b.h.i.c.client.CcuClient[:314]- Result TclRegaScript: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
2015-06-07 20:42:23.413 INFO  o.o.b.h.i.c.StateHolder[:91]- Finished loading 1062 Homematic datapoints
2015-06-07 20:42:23.414 TRACE o.o.b.h.i.c.client.CcuClient[:303]- TclRegaScript: object var_obj;
2015-06-07 20:42:23.478 TRACE o.o.b.h.i.c.client.CcuClient[:314]- Result TclRegaScript: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
2015-06-07 20:43:29.274 TRACE o.o.b.h.i.c.client.CcuClient[:303]- TclRegaScript: string dev_id;
2015-06-07 20:43:41.678 TRACE o.o.b.h.i.c.client.CcuClient[:314]- Result TclRegaScript: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>

Loading the datapoints always took longer than 5 secs, but that wasn't a problem.
The second script also takes 12 seconds, probably it is the same script, I didn't look into it. Anyway, where I previously had timeouts was here:

2015-06-02 22:30:03.620 ERROR o.o.b.h.i.c.HomematicCommunicator[:96]- Could not start Homematic communicator: Read timed out (sending BinRpcRequest[methodName=init,args={binary://10.0.1.41:9123,BidCos-RF}])

which on failing OH starts always came 5000ms after

2015-06-02 22:29:58.609 INFO  o.o.b.h.i.c.s.BinRpcCallbackServer[:44]- Starting BinRpcCallbackServer at port 9123

Now with trace log enabled I guess the interesting part is

2015-06-07 20:42:23.612 TRACE o.o.b.h.i.c.c.BinRpcClient[:191]- Client BinRpcRequest BinRpcRequest[methodName=init,args={binary://10.0.1.41:9123,BidCos-RF}]
2015-06-07 20:42:27.632 TRACE o.o.b.h.i.c.c.BinRpcClient[:199]- Client BinRpcResponse: 
2015-06-07 20:42:27.633 TRACE o.o.b.h.i.c.c.BinRpcClient[:191]- Client BinRpcRequest BinRpcRequest[methodName=init,args={binary://10.0.1.41:9123,BidCos-Wired}]

(I added the call for BidCos-Wired because I think this is the only indicator that the previous response matches the call for BidCos-RF)
In this example, the call took 4020ms, which would have been within the original timeout frame, and the start would have been successfull. But, from time to time, the call takes longer, and then the timeout occurs.

**Comment by gerrieg** [comment] 2015-06-08 14:33
OK, it's the init method. That's possible, because the init method returns all available devices. I raised the connection timeout now to 15000ms, that should be enough.

**Comment by teichsta** [comment] 2015-06-13 22:49
am i right that we can close this issue due to #2703?

**Comment by teichsta** [comment] 2015-06-18 21:11
assuming #2703 fixed this issue!

**Closed** 2015-06-18 21:11 UTC
Labels: enhancement
