### ISSUE TITLE
Multiple Time cron expressions in rule not working

### ISSUE THREAD

**Issue by phen0** [openhab/openhab#2524] opened 2015-04-30 19:05 UTC
Hi,

got an issue with multiple Time Cron rules. Either one or none is executed if there are multiples Time Cron expressions in one rule.

E.g.:

Time cron "0 6 7 ? \* MON-FRI" or
Time cron "0 22 8 ? \* MON-FRI"

Does not work properly. Sometimes it does but most of the time the rule does not work!
Thanks, Manuel
##

**Comment by msth** [comment] 2015-06-12 08:24
I've got the same Problem. Following rule executes only at changes by sunrise and sunset changes.

when
        Item Sunset_Event  received update ON or
        Item Sunrise_Event  received update ON or
        Time cron "0 0 10 * * ?" or
        Time cron "0 30 6 * * ?"
then

**Comment by LukeOwncloud** [comment] 2015-10-31 19:08
Similar problem here. Morning crons work, afternoon crons don't.

	when
		Time cron    "0 31 05 ? * *" 
		or Time cron "0 31 07 ? * *"
		or Time cron "0 31 08 ? * *"
		or Time cron "0 24 09 ? * *"
		or Time cron "0 45 17 ? * *"
		or Time cron "0 45 19 ? * *"
	then
		logInfo("log", "cron fired")

Here a German discussion of others with the same problem: http://knx-user-forum.de/forum/supportforen/openhab/35731-mehrere-time-cron-in-rules-nicht-alle-werden-ausgef%C3%BChrt

Proposed workaround:

	//define in *.items: Switch Event
	rule "Cron 1"
	when
		Time cron    "0 31 05 ? * *" 
	then
		Event.postUpdate(ON)
	end

	rule "Cron 2"
	when
		Time cron    "0 31 07 ? * *" 
	then
		Event.postUpdate(ON)
	end

	...

	rule "Event fired"
	when
		Item  Event changed to ON
	then
		Event.postUpdate(OFF)	
		//TO WHAT YOU WANT TO DO.	
	end

**Comment by 9037568** [comment] 2015-11-01 03:39
I set up the rules shown by @phen0 and @msth. They both worked fine for me using the 1.8.0 snapshot.

I'll try the set up shown by @LukeOwncloud tomorrow...

**Comment by LukeOwncloud** [comment] 2015-11-01 05:47
The problem only occurs occasionally. You need to test a few days in a row.

**Comment by 9037568** [comment] 2015-11-01 13:22
I didn't see any indication in the foregoing discussion that the problem was intermittent, but OK, noted.  Would you say this is a problem that only occurs after the system has been running for several days?

Also, perhaps you could provide some information about the platform you're running...

**Comment by LukeOwncloud** [comment] 2015-11-02 08:15
Yes, the problem is more likely to occur after the system has been running for several days. I also noticed that after this problem occured just restarting openHAB did not help. I did not restart the OS though. I'll give it a try and report back.
What seems to "repair" the issue (at least for a time) is to change the cron time (which is not working). E.g. instead of ``"0 30 07 ? * *"`` one minute later ``"0 31 07 ? * *"``

I am running openHAB version 1.8 on

    luke@home:~$ uname -a
    Linux home 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
	
	luke@home:~$ java -version
	java version "1.8.0_60"
	Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
	Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Maybe note mentioning:

My .rules file is almost 30kb in size and counts 707 lines. The file grew over time. I only noticed the problem recently. I cannot tell for sure, however, whether the problem already occured when the file was smaller. Reason: It is my heating pump which was disable during the summer.
The lines causing this issue are about in the middle of the files (around line 370).

Any data else I can provide?

**Comment by LukeOwncloud** [comment] 2015-11-03 08:28
News: I create a new file ``cron.rules``

	rule "cronDedicated issue check"
	when
		Time cron    "0 31 05 ? * *" 
		or Time cron "0 31 07 ? * *"
		or Time cron "0 31 08 ? * *"
		or Time cron "0 45 17 ? * *"
		or Time cron "0 45 19 ? * *"
	then
		logInfo("cronDedicated", "cron executed.")
	end

All cron events are executed as supposed to.

I also added the same block to the other file. It is not executed there. I'll try to add succesively more  data from the orignal, large file to `cron.rules`. Stay tuned!

**Comment by LukeOwncloud** [comment] 2015-11-05 07:02
Restarting the computer seems to help. Both cron blocks are being executed reliably for already 1.5 days. I keep them running now.

**Comment by 9037568** [comment] 2015-11-13 02:20
I let mine run for a week, and it never missed a single event.

**Comment by LukeOwncloud** [comment] 2015-11-13 07:44
Yepp, same here. Maybe it was a syntax error which I removed? But could such a typo cause undeterministic behavior? I will continue my tests...

**Comment by JCT250** [comment] 2015-12-15 03:48
Hi Luke. 

How's the stability been over the last month? Wondering if you still have the same issue. I noticed last night that two time triggered rules weren't firing, I'm pretty sure the code is solid..

**Comment by LukeOwncloud** [comment] 2015-12-15 16:00
My test is still running without failure. Everything works just as it is supposed to be. It am clueless what might be causing this issue and when it is caused at all. All in know so far: Restarting the computer seems to help (for a while of unknown length). If there weren't so many reports about the same issue I'd call for closing this issue. However...
One other thing: I think that all reporters mentioning this problem areas running some version of Linux.

**Comment by Marty56** [comment] 2016-01-02 04:35
Bug has occurred after about 8 days of operations. (Windows 10).

**Comment by grubsol** [comment] 2016-02-19 21:08
Same issue on my side running Ubuntu 14.04. Seems to be sporadic (~5 Times per month)
Rule:
```rule "lights off"
when
  Time cron "0 45 23 * * ?" or
  Item sunrise received update ON
then	
  sendCommand (lights,OFF)
end```

Interestingly when changing the order within the when-statement everything runs fine - meanwhile for more than a month.

**Comment by pvizeli** [comment] 2016-04-23 19:35
+1

**Comment by garycactuslab** [comment] 2016-05-09 21:57
I'm also experiencing this. Rules with multiple cron expressions seem to fail about half of the time.

**Comment by tarlen** [comment] 2016-05-09 21:58
I'm also experiencing this. Rules with multiple cron expressions seem to fail about half of the time.

**Comment by empi89** [comment] 2016-06-11 13:01
I also experience this issue with current OH 1.8.3.

**Comment by svenwiegand** [comment] 2016-07-17 06:49
Same problem here: Rule with two ored "Time cron" expressions plus two other triggers. Timers fired on old openHAB version (some 1.7.*) reliable for more than a year. After updating to 1.8 the Time crons didn't work anymore. After changing the cron time by a few seconds, it worked for a few days and now the timers are not firing anymore again.

Will try to split them into single rules (which will mess up my rule file) and see whether it works then.

**Comment by andrasj** [comment] 2016-11-23 18:07
Same here, I'm an openHAB beginner, but the quick tests I did, it seems only the first rule is fired.
Used testrule:
rule "test cron"
when
Time cron  "0/20 * * * * ?" or
Time cron  "10/20 * * * * ?"
then
logInfo("log", "cron fired")
end

This results in a logmsg every 20 seconds (0,20,40)
switching order of 'Time cron' definitions yields same result, but loglines appear on second 10,30,50
(running OH2 docker container on Synology NAS), same result after restarting the container, also same result after restarting the NAS

**Comment by 9037568** [comment] 2016-11-24 00:03
No further releases are planned for the 1.X platform.

**Closed by 9037568** 2016-11-24 00:03 UTC
Labels: bug, wontfix
