### ISSUE TITLE
Openhab designer issue

### ISSUE THREAD

**Issue by Totche** [openhab/openhab#2365] opened 2015-03-25 20:21 UTC
Hello,

I have just installed openhab runtime, and  the demo, working fine both.
But now i'm stuck with open designer. Configuration is ok with openhab.cfg but I get these errors with the embedded browser

![tt](https://cloud.githubusercontent.com/assets/8840194/6834461/a785cb5a-d334-11e4-99fe-c149d8231dcd.jpg)

I'm using W7 x64, and java 8 update 40.

Any tips to fix the problem ?

Thanks

**Comment by udo1toni** [comment] 2015-03-29 10:02
Don't use the embedded Browser ;) 
The Problem is, the embedded Browser is set to Mozilla for strange reasons (at least for me, as Mozilla is not a webkit browser) but luckily you don't need the embedded browser. To get rid of, just replace the embedded Window outside the Designer and close it.

**Comment by kaikreuzer** [comment] 2015-07-17 20:11
I second @udo1toni and close this issue :-)

**Closed by kaikreuzer** 2015-07-17 20:11 UTC
