### ISSUE TITLE
BasicUI Items formatting disappear after getting update/refresh from corresponding thing

### ISSUE THREAD

**Issue by mohsh86** [openhab/openhab#4362] opened 2016-05-09 23:34 UTC
Using Chrome and Basic UI, Items formatting disappear after getting update (or refresh interval elapses) from corresponding thing.

Refreshing the page brings back the proper formatting.

The issue DOES NOT happen with Classic UI, so i believe this isn't binding related.
An example is Yahoo weather outside temperature (demo), the unit "C" disappears.
Another example is NTP datetime item, it reverts back to default formatting example (2016-05-10T02:25:16.209+0300)

* Version used: (openhab 2.0.0 SNAPSHOT download 10/May/2016, binding-yahooweather - 0.8.0.SNAPSHOT, binding-ntp - 0.8.0.SNAPSHOT)
* Chrome Version 50.0.2661.94 (64-bit) . FireFox 46.0, both running on Ubuntu 16.04 (64 bit). 
* Operating System Raspbian Jessie

![screenshot from 2016-05-10 02-33-08](https://cloud.githubusercontent.com/assets/5351985/15131319/919b59ce-1657-11e6-8f3a-eeb8d4d891bf.png)

**Comment by kaikreuzer** [comment] 2016-05-10 06:27
Duplicate of https://github.com/eclipse/smarthome/issues/1166

**Closed by kaikreuzer** 2016-05-10 06:27 UTC
