### ISSUE TITLE
support vector based grapfics (svg) for icons

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#2666] opened 2015-05-30 10:10 UTC
like mentioned in this issue (https://github.com/openhab/openhab/issues/636) I think it would be nice if openhab would support svg files as icons.

This would make the look much cleaner.
Especially on high density displays.

**Comment by kaikreuzer** [comment] 2015-06-01 12:18
Duplicate of https://bugs.eclipse.org/bugs/show_bug.cgi?id=463518.

**Closed by kaikreuzer** 2015-06-01 12:18 UTC
