### ISSUE TITLE
Milight binding

### ISSUE THREAD

**Issue by sveco** [openhab/openhab#4043] opened 2016-02-13 22:30 UTC
Having trouble with milight binding. Wireshark grab of CORRECT packet (from milight app):
0000   ff ff ff ff ff ff 84 7a 88 56 3b 1f 08 00 45 00  .......z.V;...E.
0010   00 26 00 00 40 00 40 11 b5 ec c0 a8 01 8b c0 a8  .&..@.@.........
0020   01 ff bf 03 bf 03 00 12 33 25 4c 69 6e 6b 5f 57  ........3%Link_W
0030   69 2d 46 69 00 00 00 00 20 20 20 20              i-Fi....    

and incorrect from openHab:
0000   ff ff ff ff ff ff b8 27 eb 6d 8a 87 08 00 45 00  .......'.m....E.
0010   00 1f 1c 48 40 00 40 11 99 d3 c0 a8 01 63 c0 a8  ...H@.@......c..
0020   01 ff d6 21 bf 03 00 0b 44 ff 4c 00 55 00 00 00  ...!....D.L.U...
0030   00 00 00 00 00 00 00 00 00 00 00 00              ............

Milight app has set address 192.168.1.98 port 8899, but in Wireshark log i see the app sends UDP to 192.168.1.255 port 48899 (and it works). I set port to 48899 in config and ip to 192.168.1.255, but i see packets from openHab identified as SKYPE malformed packet.

**Comment by hmerk** [comment] 2016-02-14 16:56
This sounds not to be a problem with the binding in general.
What type of milight bridge are you using.

**Comment by sveco** [comment] 2016-02-14 21:43
The webUI says it's version V1.0.04a-JCY-1, so i can only guess it is v4. This is the setting:
![milight](https://cloud.githubusercontent.com/assets/2922684/13036616/3cc18cda-d36c-11e5-8c23-a694438adb90.png)

**Comment by hmerk** [comment] 2016-02-15 10:07
Can you send a picture of the bridge.

**Comment by sveco** [comment] 2016-02-15 20:19
Sure, added it to original post.

**Comment by teichsta** [comment] 2016-02-19 19:10
any advice how to proceed with this issue @hmerk?

**Comment by hmerk** [comment] 2016-02-19 19:47
To be honest, I don't have a clue.
According to the api, the port settings are correct.
It even surprises me that the bridge seems to ignore it's own settings as seen in the screenshot.
@sveco could you send the log where openhab reports the packets as malformed SKYPE packets.

**Comment by hmerk** [comment] 2016-02-25 18:29
I had another look at the API and fount out, that the wrong port your bridge reacts to is the admin config port. 

> ==================================================================
==== LimitlessLED WIFI Bridge Auto Discovery ADMIN PORT 48899 ====
==================================================================
- Step 1:Send UDP message to the LAN broadcast IP address of "10.10.100.255" and port of 48899 => "Link_Wi-Fi"
- All Wifi bridges on the LAN will respond with their details. Response is "10.10.100.254, ACCF232483E8"


So we don't have an issue with the binding, ther is a problem with your bridge.

**Comment by sveco** [comment] 2016-02-25 18:39
Thanks for the info. I will try with another bridge, i hope with more luck.
I will keep you posted. Thank You.

**Comment by riker09** [comment] 2016-04-06 20:09
Did you ever find a fix for this? I think I'm facing the same issue. I tried the OSX app [Packet Sender](https://packetsender.com/) and was able to send the commands to the bulbs (successfully tested on/off and dimming). But nothing when doing the same things from OpenHab. I do have the same software version (V1.0.04a-JCY-1)

**Comment by hmerk** [comment] 2016-04-06 21:12
According to the API, the binding is working correct, so no fix needed.

**Comment by sveco** [comment] 2016-04-07 08:09
I have not found a solution. As hmerk pointed out, it looks like bridge is ignoring it's own settings. Strange thing is that the application has no problems whatsoever to control bulbs, and given that you managed to make it work via packet sender makes me think there could be workaround. I will post full wireshark logs of communication between the app and the bridge, maybe we can figure it out whet is the problem.

**Comment by hmerk** [comment] 2016-04-08 07:12
I am closing this issue as it is not related to the binding but seems to be a problem with the V4 bridges.

**Closed by hmerk** 2016-04-08 07:12 UTC

**Comment by riker09** [comment] 2016-04-18 19:33
Sorry to bother you again, but I'm not sure if it really is an issue with the bridge. Here's a captured packet from the Milight App:

```
0000   ac cf 23 53 da 8a 38 c9 86 13 5d bd 08 00 45 00
0010   00 1e 8d 70 00 00 3f 11 00 00 c0 a8 b2 14 c0 a8
0020   b2 22 ab 3d 22 c3 00 0a 0a 51 42 00
```

The destination port seems correct (8899). I have connected my phone with the OpenHab app to the WiFi connection of my Desktop computer, which is connected to my router via ethernet.

What I noticed is, that the command itself is missing the last byte. For instance, the MiLight app sends `4800` while the api says `480055`. Both commands worked, nonetheless.

I'm still trying to figure out a way how I can caputure the packets that my OpenHab instance is sending out.

**Comment by hmerk** [comment] 2016-04-18 20:47
In
https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBinding.java#L512
you can see that the Binding sends the full message 48:00:55, which ist following the api, same in
https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBinding.java#L701

This can be proved by running openHAB in debug mode.

**Comment by riker09** [comment] 2016-04-19 05:34
I'll try to run openHAB in debug mode and will post the results here. I think you are right and that there is nothing wrong with the binding. But it would benefit everybody with a v4 bridge, if we could figure out, what the problem is about.

**Comment by hmerk** [comment] 2016-04-19 09:53
Please move the discussion over to the community, as there might be more interest/feedback from other users.

**Comment by sveco** [comment] 2016-04-19 10:27
You are right, this looks like issue described [here](https://community.openhab.org/t/problems-controlling-my-milight-bulb/5381). We will continue to discuss it on community portal.
