### ISSUE TITLE
Zipato RGBW Bulb Color Channels

### ISSUE THREAD

**Issue by KugeLSichA** [openhab/openhab#2150] opened 2015-02-17 17:45 UTC
Zipato RGBW Buld is only working with white color as dimmer...

Color is not changeable...

maybe here is a help for a workarround?!

http://www.vesternet.com/resources/application-notes/apnt-91

**Comment by cdjackson** [comment] 2015-02-17 17:55
This is a duplicate of #2083 discussion and will be implemented in the (hopefully near) future.

**Comment by cdjackson** [comment] 2015-02-18 11:20
@hlat @KugeLSichA - this is still work in progress and there's a few things to sort out yet with the conversions so that it can actually be used. I also have some uncertainty about how to actually set the colours - I've currently implemented this as one color at a time (as per the Vesternet note) but I'm sure it can support multiple colours in the same packet which is obviously a lot more useful!

So, my plan is to look at providing you something to test this weekend - I want to get the initialisation code merged first and I plan to do that tomorrow.

**Comment by KugeLSichA** [comment] 2015-02-18 16:24
@cdjackson wow that is fast support... thank you very much!!! cant wait to have this files for testing :o)

i´m fairly new to OH ... and atm the only thing i can do is testing with diff. z-wave devices... 

if this change is live... how do we call the color code?   would you be so kind and give us some code examples?!

Thanks for your help with this...!

**Comment by cdjackson** [comment] 2015-02-18 16:31
It's not complete yet - there's more work to do to get it working properly so it can be used with an item. The idea though is you'll be able to use it with the Color widget in a sitemap - with the color item type...  I may need to implement something for testing though - we'll see. I've tried to buy one to allow me to test this out, but I can't find anywhere in the UK who has one...

**Comment by KugeLSichA** [comment] 2015-02-18 16:44
sounds really good to me... i hopefully was thinking of this function, to be used with the color wheel... 

i´ve got my bulb from amazon.de  maybe amazon.co.uk have this available? or ebay.co.uk?

otherwise i can help you with testing... just let me know...

Thanks!

**Comment by cdjackson** [comment] 2015-02-18 16:49
I looked at amazon.co.uk, but it’s showing out of stock. I’ll look on eBay… If I can’t dig one up, I’ll probably add some debug routines and look for feedback from you :)

Thanks

Chris

**Comment by hlat** [comment] 2015-02-18 20:14
What about Zwave Europe?

Von meinem iPhone gesendet

**Comment by cdjackson** [comment] 2015-03-22 21:17
Work in progress still - am trying to test this with the Fibaro RGBW which is also supporting this class but it's not clear what it's doing. I have made some progress though and I hope to get some routines sorted in the next week or two to allow testing...

https://github.com/openhab/openhab/pull/2349

**Comment by KugeLSichA** [comment] 2015-03-22 21:52
@cdjackson great news.,.. thanks Chris... cant wait to test this :) THANKS!

**Comment by cdjackson** [comment] 2015-08-01 13:52
Merging this into the OH2 branch.

**Comment by cdjackson** [comment] 2015-08-09 21:55
This class will be available in the OH2 binding when it's released soon - I probably won't add it to the OH1 binding though (he says waiting for everyone to complain :) ).

**Comment by avdleeuw** [comment] 2015-08-11 05:26
Complaining wouldn't be fair :)  But.... it would still be nice to have it in OH1, so maybe I'll have to find some time to see if I can do it myself (prob. not!!!) 

Can you give some pointers to the difficulties you'd expect in making this available in OH1? You did mention incompatible types, can you elaborate on that?

**Comment by cdjackson** [comment] 2015-08-11 06:24
The command class itself should be usable with nearly no change (but not the one you've commented on - this is out of date). The more complex part is the converter(s). In OH2 I've simplified the converter concept - partly because OH2 has a different concept for items within the binding (now channels), and partly because the OH1 converter concept is (IMHO!) unnecessarily overly complicated and convoluted. 

That's not to say that creating a set of converters this back into OH1 would be extremely difficult - especially for a limited number of data types, but I don't currently have an OH1 system running (since my server died a month or so back, I changed to OH2 for my production system), and the last version of OH1 will be released reasonably soon so I just prefer to spend time on the newer version...

**Comment by KugeLSichA** [comment] 2015-08-14 21:55
@cdjackson hey chris... was really busy the last months.... so.. the color class is working on OH2?  if so... thats THE reason to update to OH2 for me...

**Comment by hlat** [comment] 2015-08-15 07:57
True - but looking forward to testing the new aeon labs bulb. Zipato bulb was not satisfying.

Von meinem iPhone gesendet

**Comment by cdjackson** [comment] 2015-08-15 08:14
Yes. This is working in oh2, but currently I've not released an oh2 binding as I need some functionality from the ESH core to allow me to provide an interface for setting associations. This is under discussion in the ESH forums and as soon as a way forward is agreed I'll get it added. 

Also agree that the Zipato bulb is a little on the dim side, but it does work nicely I think. 

Is the Aeon bulb available in Europe?

**Comment by avdleeuw** [comment] 2015-08-15 08:25
The Aeon bulb is available in Europe, Chris... I've got one working as a
regular dimmed bulb at the moment... can't wait for the colours :)

**Comment by cdjackson** [comment] 2015-08-15 09:08
Does the Aeon have an option to stay off after a power cut? The Zipato will come on after a power cut even if it was off before the outage? Very annoying (Hue bulbs also do this!)

**Comment by avdleeuw** [comment] 2015-08-15 09:11
I alreade knew the bulb stayed off after a power cut when it was off
before... as my wife isn't used to NOT using the switch anymore :) Just did
a test with a lighted bulb and a power cut.... it turns on again if it was
on before.

**Comment by cdjackson** [comment] 2015-08-15 09:17
Thanks - that’s useful. I might get one (I see my ‘local’ UK supplier I use has them).

**Comment by hlat** [comment] 2015-08-15 15:02
How often do you have power outages ;-) hues work with physical  Switches too- Zipato not, hope the aeon does.

Von meinem iPhone gesendet

**Comment by cdjackson** [comment] 2015-08-15 15:06
> 
> How often do you have power outages ;-)

It’s a bit better now - about once every couple of weeks, but we went through a period where it was about once a week… I live slightly out in the country, but still only about 50km from London - it should be reliable! :)


> hues work with physical Switches too- Zipato not, hope the aeon does. 

What do you mean? The Zipato seems to be ok with a physical switch - what would stop it working with a switch? (or maybe I should read the manual! :) ).

**Comment by hlat** [comment] 2015-08-15 16:42
It did not work for me to turn it Off and then on only with a physical switch (Turning Off worked obviously). If a hue is turned off via App and you turn the physical switch once Off and on it lights up in standard white.

Von meinem iPhone gesendet

**Comment by cdjackson** [comment] 2015-08-15 16:45
Hmmm - I’ll check that here. I thought it worked, but maybe I was doing something slightly different… I thought it always came on when I used the physical switch…

**Comment by anordvall** [comment] 2015-10-01 17:57
If I turn my Aeon Labs RGB LED bulb off and then also turn the physical switch off, the lamp will turn on again as soon as I turn the physical switch on. How do you do it differently Ard? :)

**Comment by avdleeuw** [comment] 2015-10-02 05:48
Uh oh... your message triggered me to give another try, with interesting results...

I've got 4 of these bulbs installed in our house at the moment. Three of them are connected to a single power switch, and the other one has a separate switch. 

The single bulb will NOT switch on after toggling power. 

For the three other bulbs, when I toggle power, TWO of them turn on, while ONE of them stays off. Interesting behaviour... and it would make me believe this might be configurable behaviour

**Comment by anordvall** [comment] 2015-10-09 18:32
The needed config parameter for that (for the Aeon bulb) will hopefully be added as part of https://github.com/openhab/openhab/issues/3253 :)

**Comment by cdjackson** [comment] 2015-10-09 18:35
What do you mean?  This issue is not related to #3253 at all.

**Comment by anordvall** [comment] 2015-10-09 18:40
I was referring only to the last couple of comments regarding the behavior of the Aeon Labs bulb at physical switch on/off. Isn't that related either? Sorry for the confusion either way.

**Comment by cdjackson** [comment] 2015-10-09 19:05
I’m not sure - I’ve not seen the manual yet, so I’m not sure if there’s a config item. It just gets a little confusing linking the color channel command class to the configuration since this isn’t linked…

Anyway, no probs - I was just wanting to make sure people didn’t expect this issue to be closed simply by adding the configuration.

**Comment by chailer** [comment] 2015-10-21 14:18
Hi Chris, is there a way to test your colour command class with OH2 yet?

**Comment by cdjackson** [comment] 2015-10-21 16:02
No - not yet. I am working on getting the final changes made to the binding, but it’s taking a bit of time.

https://www.eclipse.org/forums/index.php/t/1066227/ <https://www.eclipse.org/forums/index.php/t/1066227/>

**Comment by TrevorNewsome** [comment] 2016-01-09 18:22
Has anyone implemented the colour functionality for the Zipato RGBW blub? If so would you be so kind as to add an example of the bindings please.

Thank you for your time Trev

**Comment by cdjackson** [comment] 2016-01-09 18:23
No - it is not available in the OH1 binding.

**Comment by tjerkw** [comment] 2016-03-21 13:00
So im thinking of buying either the Zipato RGBW or the AeonLabs RGBW bulb. Is this working fine  in OH2? If so, then i can buy them. Greetings

**Comment by cdjackson** [comment] 2016-03-21 13:24
Yes, I think both are usable on OH2. I personally have the Zipato, and we have also tested the Aeon.

**Comment by tjerkw** [comment] 2016-03-24 22:57
Ok i have difficulty connecting the discovered lamp (Thing) to an Item. (Color item)... The zipato RGBW actions are not recognized. I do see a userdata/zwave/node5.xml being generated, which correctly describe the Zipato RGBW lamp. However in the "paper ui" i cannot bind it to a item, since the actions of the thing are not regonized... Where is the documentatino for manually bindign the Thing, Color command to an Color item in the .items file?

**Comment by cdjackson** [comment] 2016-03-24 23:00
Can I suggest discussing this on the forum - this is the OH1 bug list so I don't think you're going to get a particularly wide audience...

**Comment by tjerkw** [comment] 2016-03-24 23:32
Good point.

**Comment by cdjackson** [comment] 2016-04-06 21:51
Closing this as won't be implemented in OH1

**Closed by cdjackson** 2016-04-06 21:51 UTC
Labels: enhancement, wontfix
