### ISSUE TITLE
All DMX Bundle Tests throw Exception but tests are reported as successful

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab#1807] opened 2014-12-07 09:52 UTC
All tests of the DMX Bundle (binding.dmx.test) terminate with an Exception (BindingConfigParseException), see Build server log:
https://openhab.ci.cloudbees.com/job/openHAB/org.openhab.binding$org.openhab.binding.dmx.test/790/consoleFull

However, all tests are reported as successful finally:
Results :
Tests run: 35, Failures: 0, Errors: 0, Skipped: 0
[INFO] All tests passed!

So, there seem to be two issues here:
1) DMX Bundle Tests fail
2) Tests are reported as successful even though Exceptions are thrown

**Comment by dvanherbergen** [comment] 2016-01-26 20:27
This is not a bug. The exceptions are expected and printed as part of the test case. @steve-bate can you close this issue?

**Closed** 2016-01-26 20:32 UTC
Labels: bug
